[뽀또] 1, 2단계 영화 극장 선택 제출합니다.
woowacourse/android-movie-theater pull request #22
Opened 2023-04-27 08:47 UTC by hyunji1203

레아!!!!! 안녕하세요!!!
이번에 드디어 레아와 함께 미션진행하게 되어 너무 신나고 행복해요😁
페어와 함께 영화 극장 선택 미션 구현해보았습니다!
미션을 진행하면서 궁금한 점이 생겼는데요..!

AlarmManager를 사용해 알람을 생성하는 로직의 함수를 클래스로 따로 빼고 싶었는데, 만약 이렇게 된다몀 해당 클래스에 context를 넘겨 줘야하는 상황이 발생하더라고요... 이렇게 클래스에 context를 넘겨주는 것이 괜찮은 로직일까요?

2023-04-28 07:17 UTC, woowahan-leah requested changes
안녕하세요 뽀또! 이렇게 만나게 되어 반갑습니다 👋 

1, 2단계 구현을 잘 해주셨습니다 💯  깔끔한 구현이 좋았습니다
고민해보시면 좋을만한 코멘트를 달았으니 확인해주시면 감사하겠습니다.

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 💪

2023-04-28 07:17 UTC, woowahan-leah commented on README.md
<img width="333" alt="image" src="https://user-images.githubusercontent.com/112997521/235064680-90af5268-f891-4ef6-a998-da5c5f88a240.png">

프로젝트가 커지면서 슬슬 프로젝트 구조에 대한 고민을 할 필요가 있어요!
activity, fragment 단위로 프로젝트 구조를 나누면 나중에 화면이 더 늘어난다면 유지보수하기 어려워지지 않을까요?

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/AlarmReceiver.kt
> +        settingPreference = SettingPreference(context)
> AlarmManager를 사용해 알람을 생성하는 로직의 함수를 클래스로 따로 빼고 싶었는데, 만약 이렇게 된다몀 해당 클래스에 context를 넘겨 줘야하는 상황이 발생하더라고요... 이렇게 클래스에 context를 넘겨주는 것이 괜찮은 로직일까요?

클래스에 context를 넘겨주어 인스턴스를 만들 필요가 있는 경우도 있습니다! 다만 이 상황에서는 SettingPreference가 매번 receive될 때마다 인스턴스화될 필요가 있는지 고민해볼 필요가 있습니다 🤔

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/AlarmReceiver.kt
> +            val bookingMovie = intent.getSerializableExtra(BOOKING_MOVIE_KEY) as BookingMovieDto
getSerializableExtra에 deprecated warning이 뜨고 있네요!

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/AlarmReceiver.kt
> +    private fun createNotificationPendingIntent(
Notification을 관리하는 별도의 객체를 만들어 재활용할 수 있도록 해보면 어떨까요?

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/SettingPreference.kt
> +        set(value) = sharedPreferences.edit().putBoolean(setting_value_key, value).apply()
setting의 setter를 구현하여 외부에서 편하게 값을 조작할 수 있도록 했는데요, 별도의 부수 효과가 있는 동작을 하는 경우 setter보다는 일반 함수를 고려하는게 좋다고 생각해요. 개발자마다 의견이 다를 수 있을 것 같은데 뽀또는 어떻게 생각하시나요? 🙂

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/activity/MainActivity.kt
> +                        supportFragmentManager.commit {
depth가 너무 깊어요!!!

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/activity/MainActivity.kt
> +                            replace(R.id.fragment_container_view, HistoryFragment())
매번 이렇게 Fragment를 생성해줘야 할까요? 
현재 상태라면 영화 리스트 화면의 스크롤이 탭 전환시마다 초기화됩니다. 이미 생성한 Fragment를 재활용할 방법은 없을까요?

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/activity/MainActivity.kt
> +    }
힌트 코드를 그대로 복사하기보다 상황에 맞게 커스텀하면 어떨까요! 😆

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/activity/SeatSelectionActivity.kt
> +        }
영화 티켓 예매 미션 1, 2단계 피드백에서 Calendar대신 다른 API 사용을 권장했었는데, 다시 한 번 살펴보면 어떨까요?

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/activity/SeatSelectionActivity.kt
>      }
이러한 코드도 Activity에서 직접 호출하기보다 해당 역할을 담당하는 객체를 따로 만들어보면 어떨까요?

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/dto/movie/BookingMovieDto.kt
> +data class BookingMovieDto(
DTO 네이밍을 사용해주셨는데요, 사실 엄연히 말하면 이 객체는 DTO라고 부르기 어렵습니다 🤔 
개발 과정에서 네이밍 정하는게 제일 까다롭기도 한데요... 제가 선호하는 네이밍 스타일을 참고로 달아둡니다!

https://github.com/PRNDcompany/android-style-guide/blob/main/Architecture.md#model-mapping-%EC%A0%95%EC%9D%98%EA%B5%AC%EC%A1%B0

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/dto/movie/BookingMovieDto.kt
> +) : java.io.Serializable
Serializable을 선택하신 이유가 무엇일까요? 🙂

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/dto/seat/SeatRowDto.kt
> +        fun of(row: Int): SeatRowDto = SeatRowDto((row + 64).toChar())
domain의 Grade를 활용하여 값을 판단하면 어떨까요?

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/fragment/HistoryFragment.kt
> +    }
1. history_rv -> 코틀린에서는 값에 스네이크 케이스를 사용하지 않습니다!
2. HistoryRVAdapter -> 꼭 필요한 경우가 아니라면 약어를 사용하는 것은 피하는게 좋습니다. 다른 개발자들도 알아들을 수 있는 단어로 바꿔볼까요?
3. OnClickListener 인터페이스를 만들어서 얻을 수 있는 이점이 뭐가 있을까요? 🤔 
4. itemViewClick가 따로 초기화되어야 하는 이유가 있나요?
5. notifyDataSetChanged에서 워닝이 뜨고 있어요. 왜그럴까요?

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/fragment/SettingFragment.kt
> +    }
의미있는 단위로 함수를 나눠볼 수 있을까요?

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/history/HistoryViewHolder.kt
> +    }
bind 함수에서 setOnClickListener를 호출하면 매 바인딩마다 OnClickListener가 다시 세팅됩니다! 어떻게 개선해볼 수 있을까요?

2023-04-28 07:17 UTC, woowahan-leah commented on app/src/main/res/layout/fragment_setting.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
전반적으로 ConstraintLayout을 잘 사용해주셨네요 ㅎㅎ 혹시 xml에서 포매팅도 해주실 수 있을까요?

2023-04-29 06:43 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/AlarmReceiver.kt
> +            val bookingMovie = intent.getSerializableExtra(BOOKING_MOVIE_KEY) as BookingMovieDto
해당 deprecated warning 이슈때문에, parcelize를 사용하도록 수정했습니다!

2023-04-29 06:49 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/dto/movie/BookingMovieDto.kt
> +) : java.io.Serializable
Parcelize와 비교했을 때 속도가 상대적으로 느릴 수 있다는 문제가 있는 것을 인지 했지만 해당 규모의 프로젝트에서는 큰 차이가 없을 것 같아 처음 구현 시 사용했던 Serializable을 계속 사용했었습니다. 하지만 deprecated warning이 뜨기도 하고 장기적으로 봤을 땐 Parcelize를 사용하는게 맞다고 판단해 수정하였습니다!

2023-04-29 07:39 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/activity/MainActivity.kt
> +                        supportFragmentManager.commit {
해당 부분 코드들을 함수로 분리해 depth문제를 해결했습니다!

2023-04-29 09:25 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/history/HistoryViewHolder.kt
> +    }
`HistoryAdapter` 클래스에서 해당 `setOnclickListenter`가 호출되도록 수정했습니다!

2023-04-29 09:39 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/fragment/SettingFragment.kt
> +    }
`onCreateView`안에 있던 스위치 관련 로직들을 `bindSwitch` 함수로 분리했습니다!

2023-04-29 10:13 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/activity/SeatSelectionActivity.kt
> +        }
넵! Calendar말고 LocalDateTime API를 통해 시간을 계산하도록 수정했습니다!

2023-04-29 16:42 UTC, hyunji1203 commented on app/src/main/res/layout/fragment_setting.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
네!! xml 포매팅 해줬습니다!!

2023-04-30 04:46 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/activity/SeatSelectionActivity.kt
>      }
넵! `PendingIntent`를 생성하는 클래스를 만들어 해당 역할을 담당하도록 수정하였습니다~!

2023-04-30 04:48 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/AlarmReceiver.kt
> +    private fun createNotificationPendingIntent(
넵! 이를 위해 `Notification`을 관리하는 별도의 객체 `NotificatioManager`을 만들었습니다!

2023-04-30 08:25 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/activity/MainActivity.kt
> +    }
네! 코드를 상황에 맞게 메세지를 전달할 수 있도록 커스텀시켰습니다!!

2023-04-30 08:45 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/fragment/HistoryFragment.kt
> +    }
1. 해당 변수 카멜 케이스로 변경했습니다!
2. 약어를 쓰지 않고 `HistoryAdapter`로 수정하였습니다!
3. 예를들어 영화를 선택했을 때와 광고를 클릭했을 때 다른 결과가 나올 수 있는 상황처럼 이렇게 상황에 따라 클릭 이벤트가 달라질 수 있는 케이스라면 해당 `onClickListener`함수를 인터페이스화 시키면 쉽고 확장성 있게 클릭 시 다른 이벤트를 넣어줄 수 있는 이점이 있습니다!
4. 앗… 사실 이 부분은 해당 클릭 함수 인터페이스를 구현해 넣어주기 위해 초기화를 시킨건데 이거외엔 특별히 다른 이유는 없습니다..! 
5. `notifyDataSetChanged`는 전체 항목 목록을 한 번에 변경 후 다시 바인딩 해야하는 경우에 사용되므로 성능의 저하를 일으킬 수 있어 워닝이 뜨는 것입니다! 그러므로 특정 항목이 추가되거나 변경되는 경우에는 `notifyItemChanged`같은 함수를 사용해야합니다!

2023-04-30 14:24 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/activity/MainActivity.kt
> +                            replace(R.id.fragment_container_view, HistoryFragment())
넵! 원래는 `show()`와 `hide()`기능을 통해 프래그먼트를 재활용 하려고 시도했었는데 자꾸 오류가 나서🥹.. 프래그먼트를 미리 `companion object`에 생성해놓고 네비게이션 바 클릭 시 미리 생성해두었던 프래그먼트로 대체되도록 하는 방식으로 수정하였습니다! 이렇게 재활용하는 방법 괜찮을까요?!

2023-04-30 14:54 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/dto/movie/BookingMovieDto.kt
> +data class BookingMovieDto(
달아주신 링크를 참고해 DTO말고 Entity를 붙여 네이밍 해줬습니다!
레아! 한가지 궁금한게 있어요! 왜 이 객체는 DTO라고 네이밍하기 어려울까요?!
클래스 간의 데이터 전달을 담당하고 있긴 하지만 이 외에도 다양한 곳에서 해당 객체가 사용되고 있기 때문일까요..!?

2023-04-30 15:36 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/SettingPreference.kt
> +        set(value) = sharedPreferences.edit().putBoolean(setting_value_key, value).apply()
쉽게 구현하기 위해 위와 같이 구현을 해놨지만 저도 프로퍼티의 `get`,`set`에 많은 로직이 있으면 안된다고 생각합니다! 따라서 결론적으로 이를 함수로 분리하는게 맞다 생각해 함수로 관리되도록 수정했습니다!

2023-04-30 16:32 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/AlarmReceiver.kt
> +        settingPreference = SettingPreference(context)
SettingPreference가 receive 될 때마다 인스턴스화되지 않기 위해 mainActivity의 companion object에서 선언도 해보고 SettingFragment에서도 선언해보았는데 아예 앱 자체가 실행되지 않는 오류가 떠 해당 이슈를 해결하지 못했습니다.. Preference를 생성해 사용하려면 해당 context를 집어 넣어줘야하기 때문에 사용이 될 때 그 곳에서 인스턴스화 시킬 수 밖에 없는 것인가 라는 생각도 들었습니다. 혹시 어떻게 하면 이 문제를 해결할 수 있을까요?

2023-04-30 16:43 UTC, hyunji1203 commented on README.md
기능 단위 별로 패키지를 만들어 해당 기능에 속하는 클래스들을 모아놓았고, 그외에 전역에서 활용될 수 있는 파일들은 utils 패키지에 넣었습니다!!

이렇게 우선 구조를 나눠보았는데.... 아직까지 이 구조도 맞는지는 잘 모르겠어요.. 다음 스텝에 들어가 MVP 구조에 대해 적용시키게 될 때 프로젝트 구조에 대해 다시 한번 더 고민해보겠습니다!

2023-04-30 16:58 UTC, hyunji1203 commented
레아! 주말 잘 보내고 계신가요?!😄
레아가 주셨던 피드백들을 수정하면서 위의 피드백에 달아놓은 질문들 뿐만 아니라, 두가지 질문이 더 생겼습니다!

1. `domain`의 `Grade`를 활용해 `SeatRowDto`의 값을 판단하라고 하셨는데 감이 잡히지 않아 다시 한번 더 여쭤보게 되었습니다....! 어떤 느낌으로 해야할까요?🥲

2. `Serializable`에서 `Parcelable`로 바꾸면서, 알림을 눌렀을 때 해당 티켓을 보여주는 페이지로 넘어가는 부분에서 자꾸 `android.os.BadParcelableException: ClassNotFoundException when unmarshalling` 이런 오류가 나고 있습니다.. 구글링을 해봤는데도 해결방법을 찾지 못해 죄송하지만 레아에게 여쭤보게 되었습니다.. 어떤 부분이 문제가 된 것일까요?

너무 전반적으로 질문을 많이 남긴 것 같아 죄송합니다..🥲
바쁘신 와중 피드백 감사합니다!

2023-04-30 17:39 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/dto/seat/SeatRowDto.kt
> +        fun of(row: Int): SeatRowDto = SeatRowDto((row + 64).toChar())
`domain`의 `Grade`를 활용해 `SeatRowDto`의 값을 판단하라고 하셨는데 감이 잡히지 않습니다..! 어떤 느낌으로 해야할까요?🥲

2023-05-01 14:52 UTC, woowahan-leah approved these changes
안녕하세요 뽀또! 
리뷰 반영을 잘 해주셨습니다 💯 

조금 고민해보시면 좋을 내용을 코멘트로 달았으니 다음 단계 미션 진행해주시면서 같이 반영해주시면 됩니다!
이번 미션의 핵심 중 하나인 Fragment의 전환과 재활용에 초점을 맞추면 더욱 의미있는 미션이 될 것 같아요.

다음 미션도 화이팅입니다 🙏

2023-05-01 14:52 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/MainActivity.kt
> +    private lateinit var binding: ActivityMainBinding
Binding 사용은 4단계 요구사항인데 미리 적용하셨군요! 3, 4단계 리뷰 시 참고하겠습니다.

2023-05-01 14:52 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/MainActivity.kt
> +        binding.navigationBar?.let { bindNavigationBar(it) }
```suggestion
        binding.navigationBar?.let(::bindNavigationBar)
```
다음과 같이 함수 레퍼런스를 이용해 작성할 수도 있답니다!

2023-05-01 14:52 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/MainActivity.kt
> +        )
> 넵! 원래는 show()와 hide()기능을 통해 프래그먼트를 재활용 하려고 시도했었는데 자꾸 오류가 나서🥹.. 프래그먼트를 미리 companion object에 생성해놓고 네비게이션 바 클릭 시 미리 생성해두었던 프래그먼트로 대체되도록 하는 방식으로 수정하였습니다! 이렇게 재활용하는 방법 괜찮을까요?!

괜찮지 않습니다 🥲  [다음 스레드](https://woowacourse.slack.com/archives/C04JY0TMESZ/p1682587503205879?thread_ts=1682584492.468499&cid=C04JY0TMESZ)의 대화를 참고해보세요!

2023-05-01 14:52 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/history/HistoryFragment.kt
> +            override fun onClick(item: BookingMovieEntity) {
> OnClickListener 인터페이스를 만들어서 얻을 수 있는 이점이 뭐가 있을까요? 🤔

람다로 넘길 때에 비해 큰 이점이 없는 것 같습니다. 오히려 불필요한 익명 클래스를 구현하게 되어 보일러플레이트가 더 늘어나게 된 것 같아요. 만약 [함수형 인터페이스](https://kotlinlang.org/docs/fun-interfaces.html)로 구현한다면 보일러플레이트를 줄일 수는 있을 것 같지만 람다에 비한 이점이 있을까요?
```kotlin
fun interface OnClickListener
```

2023-05-01 14:52 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/movielist/MovieViewHolder.kt
> +    private val bookButton: Button = itemView.findViewById(R.id.book_button)
4단계에서 binding을 적용하며 이 코드가 어떻게 바뀌는지 느껴보면 RecyclerView를 더 잘 이해할 수 있을거예요!

2023-05-01 14:52 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/seat/SeatSelectionActivity.kt
> +    private val ticketCount by lazy { intent.getParcelableCompat<TicketCountDto>(TICKET_KEY)!! }
1. 간단한 코드라도 `!!` 연산자는 지양하는게 좋습니다. 자칫하면 불필요한 크래시로 이어질 수 있습니다. (다른 코드에서도 이하동일합니다)
2. 생각해보면 date, time, movie, ticketCount을 모두 해체하여 intent로 넘길 필요가 있을까요? (== 새로운 값이 100개 추가되면 프로퍼티가 100개가 되어야 할까요?) 이를 모두 묶는 모델을 만들어보면 어떨까요?

2023-05-01 14:52 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/setting/AlarmReceiver.kt
> +        settingPreference = SettingPreference(context)
> SettingPreference가 receive 될 때마다 인스턴스화되지 않기 위해 mainActivity의 companion object에서 선언도 해보고 SettingFragment에서도 선언해보았는데 아예 앱 자체가 실행되지 않는 오류가 떠 해당 이슈를 해결하지 못했습니다.. Preference를 생성해 사용하려면 해당 context를 집어 넣어줘야하기 때문에 사용이 될 때 그 곳에서 인스턴스화 시킬 수 밖에 없는 것인가 라는 생각도 들었습니다. 혹시 어떻게 하면 이 문제를 해결할 수 있을까요?

SettingPreference가 인스턴스화될 필요가 없는 객체라면 object로 만들고 함수에서 context를 받도록 하면 어떨까요?

2023-05-01 14:52 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/ticket/TicketActivity.kt
> +        Log.d("test", "인텐트 값 받아오기 성공")
테스트용 로그, 주석 등은 제거해주세요! 😆

2023-05-01 14:52 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/utils/ParcelableCompatExtensions.kt
> +inline fun <reified T : Parcelable> Bundle.getParcelableCompat(key: String): T? {
Compat 네이밍 👍

2023-05-01 14:52 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/dto/seat/SeatsDto.kt
>  }
> 달아주신 링크를 참고해 DTO말고 Entity를 붙여 네이밍 해줬습니다!
레아! 한가지 궁금한게 있어요! 왜 이 객체는 DTO라고 네이밍하기 어려울까요?!
클래스 간의 데이터 전달을 담당하고 있긴 하지만 이 외에도 다양한 곳에서 해당 객체가 사용되고 있기 때문일까요..!?

DTO는 로직을 갖지 않는 순수한 계층간 데이터 교환용 객체입니다. 하지만 뽀또가 만들어주신 객체는 뷰를 그리기 위한 함수를 활용하는, "뷰"에 대한 객체입니다. DTO라는 네이밍을 사용하기에는 적절하지 않다고 생각했어요! 뽀또는 어떻게 생각하시나요?

2023-05-01 14:52 UTC, woowahan-leah commented on app/src/main/java/woowacourse/movie/movie/dto/seat/SeatRowDto.kt
> +        fun of(row: Int): SeatRowDto = SeatRowDto((row + 64).toChar())
다시 질문을 드려볼게요! 첫 번째 행, 첫 번째 열의 좌석이 A1로 표시되는 것은 뷰 로직인가요? 도메인 로직인가요?

2023-05-01 14:52 UTC, merged

2023-05-02 06:25 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/seat/SeatSelectionActivity.kt
> +    private val ticketCount by lazy { intent.getParcelableCompat<TicketCountDto>(TICKET_KEY)!! }
1. 넵! 해당 getParcelCompat 함수가 null을 반환하지 않도록 수정해 해당 !! 연산자가 사용될 필요가 없도록 수정하였습니다!
2. 해당 데이터들을 묶는 SeatMovieDto 모델을 새로 만들어 한번에 묶어 넘기도록 수정했습니다!

2023-05-02 07:59 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/setting/AlarmReceiver.kt
> +        settingPreference = SettingPreference(context)
넵! SettingPreference 클래스를 object 클래스로 수정했습니다~!

2023-05-02 07:59 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/ticket/TicketActivity.kt
> +        Log.d("test", "인텐트 값 받아오기 성공")
넵!

2023-05-02 08:54 UTC, hyunji1203 commented on app/src/main/java/woowacourse/movie/movie/MainActivity.kt
> +        )
프래그먼트 재활용을 위해 show와 hide로 재활용 적용시켰습니다!