[코건] 3, 4단계 영화 극장 선택 제출합니다.
woowacourse/android-movie-theater pull request #27
Opened 2023-05-05 11:46 UTC by DYGames

안녕하세요! 이번 리뷰도 잘 부탁드립니다!! 😊

### MVP
- MVP 패턴을 적용하였습니다. 이때 리사이클러뷰가 있는 프래그먼트는 리사이클러뷰 외에 다른 뷰 요소가 없어서 어댑터를 MVP의 뷰라고 생각하고 바로 어댑터에 MVP를 적용하였습니다.
- Presenter에 대한 테스트를 적용할 때, 도메인 로직에 대한 유닛 테스트가 아니므로 이에 대한 테스트는 배제하고 Presenter에서 View와 Model을 잘 이어주는지에 대한 테스트만 진행했습니다.

### 기존 예매 내역, 알람 정보 유지
- SQLite를 이용해 기존 예매 내역에 대한 스키마를 구성하고 저장하였습니다. 이때 SQLiteOpenHelper는 data module에 위치하는데, 싱글톤으로 구성하여 Application을 상속하는 클래스에서 context와 함께 인스턴스를 할당하게 하였습니다.
- SharedPrefrences에 대한 관리도 동일합니다.
- 알람 정보는 AlarmManager에 의해 앱을 껐다 켜도 유지되므로, 기기의 전원을 껐다 켰을때 재등록 할 수 있도록 BOOT_COMPLETED Broadcast Receiver에서 재할당해주었습니다.

### App -> Domain <- Data
App 모듈에서 Domain 모듈과 Data 모듈을 참조하고 있고, Data 모듈에서도 Domain 모듈을 참조하고 있습니다. Domain 모듈은 다른 모듈을 참조하고 있지 않게 하여 의존성을 제거했습니다.
Data 모듈에서는 SQLite와 SharedPreferences를 관리하게 하였습니다.

### DataBinding
- 모든 레이아웃에 DataBinding을 적용하였습니다.

---
감사합니다!

2023-05-06 06:07 UTC, galcyurio requested changes
MVP 패턴 적용과 각 역할에 맞게 data 모듈, domain 모듈로 잘 분리해주셨네요 👍 👍 
이번 단계에서는 의존성 주입에 초점을 맞춰서 피드백을 반영해보시면 좋겠습니다.

이미 반영할 피드백이 너무 커진 것 같아서 추가로 피드백을 더 남기지 않았는데 궁금하신 점이 있으시면 코멘트로 남겨주세요!

2023-05-06 06:07 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/contract/MovieAdapterContract.kt
> +        val onClickItem: (MovieViewData, TheatersViewData) -> Unit
콜백 함수는 변수로 선언하기보다는 함수로 선언해주세요.

2023-05-06 06:07 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/contract/MovieAdapterContract.kt
> +        fun onClickItem(movie: MovieListItemViewData)
Presenter의 함수 이름은 콜백 형태의 이름 보다는 실제로 어떤 작업을 하는지를 드러내주세요.

2023-05-06 06:07 UTC, galcyurio commented on domain/src/main/java/woowacourse/movie/domain/Theaters.kt
> +}
일급 컬렉션 활용 👍

2023-05-06 06:07 UTC, galcyurio commented on data/src/main/java/woowacourse/movie/data/database/table/SQLTable.kt
> +interface SQLTable {
코틀린에서는 `SqlTable`과 같이 class 이름은 CamelCase로 짓는게 컨벤션입니다.

2023-05-06 06:07 UTC, galcyurio commented on data/src/main/java/woowacourse/movie/data/database/MovieDBHelper.kt
> +class MovieDBHelper(context: Context) :
DB에 접근하는 객체들은 DAO(Data Access Object)라고 부릅니다.
안드로이드에서는 보통 로컬 DB에 접근하는 객체들을 `MovieDao`와 같이 이름을 지어주는 편이에요. 

https://developer.android.com/training/data-storage/room?hl=ko#dao

2023-05-06 06:07 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/presenter/MovieReservationPresenter.kt
> +package woowacourse.movie.presenter
presenter 패키지에 모든 Presenter를 모으기보다는 각 화면별로 패키지를 만들어보세요.
프로그램이 복잡해지면 복잡해질수록 feature 별로 패키지 또는 모듈을 나누는게 더 유리해집니다.

자세하게는 아래 글을 읽어보세요!
https://martinfowler.com/bliki/PresentationDomainDataLayering.html

2023-05-06 06:07 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/contract/SeatSelectionContract.kt
> +        fun initActivity(movie: MovieViewData, reservationDetail: ReservationDetailViewData)
`initActivity()`, `initFragment()`와 같은 함수들을 모두 제거하고 `init { ... }` 영역에서 처리하도록 만들어보세요.

꼭 필요한 경우에만 별도 함수로 분리해주세요.
이름 또한 Activity, Fragment와 같이 안드로이드에 의존적인 이름을 제거하고 `init()`, `initView()`와 같은 네이밍으로 지어져야 합니다.
Presenter에는 안드로이드에 관한 이름, 의존성을 포함하지 않을수록 좋습니다.

2023-05-06 06:07 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/view/activity/SeatSelectionActivity.kt
> +    override val presenter: SeatSelectionContract.Presenter = SeatSelectionPresenter(this)
Presenter의 생성은 Activity, Fragment의 생명주기에 맞춰서 생성되어야 합니다.
`onCreate()` 이벤트가 발생했을 때, Presenter를 생성하도록 만들어보세요.

2023-05-06 06:07 UTC, galcyurio commented on data/src/main/java/woowacourse/movie/data/dataSource/MovieDataSource.kt
> +        LocalDatabase.movieDBHelper?.selectAllMovies()?.toMutableList() ?: mutableListOf()
> - SQLite를 이용해 기존 예매 내역에 대한 스키마를 구성하고 저장하였습니다. 이때 SQLiteOpenHelper는 data module에 위치하는데, 싱글톤으로 구성하여 Application을 상속하는 클래스에서 context와 함께 인스턴스를 할당하게 하였습니다.
> - SharedPrefrences에 대한 관리도 동일합니다.

Application Context를 이용해서 초기화하독 싱글턴으로 호출하는 방식은 피해주시는게 좋습니다.
추후에 유지보수가 굉장히 힘들어지기 때문이에요.
만약 LocalDatabase에서 Context 의존성 이외에 다른 객체에 대해서도 의존이 필요해지는 경우 똑같이 Application Context를 사용해서 초기화하는 식으로 악순환이 이어집니다.
또한 테스트 할 때도 반드시 LocalDatabase를 초기화해야 한다는 것을 알고 있어야 하는데 그 부분이 내부 구현으로 감추어져서 코드를 읽어봐야만 알 수가 있습니다.

대신에 생성자를 통해 의존성을 주입하는 방식으로 변경해보세요.
이 피드백을 올바르게 적용한다면, 아래의 모든 클래스들은 생성자로 의존성이 드러나야 합니다.

- XxxPresenter
- XxxRepository
- XxxDataSource
- LocalDatabase

2023-05-08 05:28 UTC, DYGames commented on app/src/main/java/woowacourse/movie/contract/MovieAdapterContract.kt
> +        val onClickItem: (MovieViewData, TheatersViewData) -> Unit
멤버 콜백 함수를 제거하고 적절한 역할을 가진 함수를 추가해줬습니다. [커밋](https://github.com/woowacourse/android-movie-theater/pull/27/commits/f41a419b6a2a5a021d857ad54aa3b58e3355f5c6)

2023-05-08 05:28 UTC, DYGames commented on app/src/main/java/woowacourse/movie/contract/MovieAdapterContract.kt
> +        fun onClickItem(movie: MovieListItemViewData)
onClickItem() -> createTheaterDialog() 로 변경하였습니다. [커밋](https://github.com/woowacourse/android-movie-theater/pull/27/commits/f41a419b6a2a5a021d857ad54aa3b58e3355f5c6)

2023-05-08 05:32 UTC, DYGames commented on data/src/main/java/woowacourse/movie/data/database/table/SQLTable.kt
> +interface SQLTable {
SQL이 각각 약자여서 이렇게 표기했었습니다 😅 모든 클래스에 카멜케이스를 적용하였습니다. [커밋](https://github.com/woowacourse/android-movie-theater/pull/27/commits/7b5d009d7172b643f86e6696641a2de59433fc3b)

2023-05-08 05:35 UTC, DYGames commented on data/src/main/java/woowacourse/movie/data/database/MovieDBHelper.kt
> +class MovieDBHelper(context: Context) :
MovieDBHelper를 MovieDao로 변경하였습니다. [커밋](https://github.com/woowacourse/android-movie-theater/pull/27/commits/47a35b23d47948f3de4f0753747cea8d54bb40f9)

궁금한 점이 생겼는데, 이러한 Dao 객체는 테이블 별로 분리를 해주어야 하나요? 테이블 간에 Join이 발생하는 경우는 어떻게 설계가 되나요?

2023-05-08 05:57 UTC, DYGames commented on app/src/main/java/woowacourse/movie/contract/SeatSelectionContract.kt
> +        fun initActivity(movie: MovieViewData, reservationDetail: ReservationDetailViewData)
기본적으로 생성자에서 로직을 배제해야 한다고 생각해서 따로 init~() 함수를 만들어서 로직을 구현했습니다.
피드백을 받고 init 블럭에서 프레젠터가 생성될 때 실행되어야 할 로직들을 강제해줄 수 있다고 생각했습니다. 
액티비티의 생명주기에 맞춰 생성된 프레젠터에선 init 블럭을 통해 초기화 로직을 구현해주었습니다. [커밋](https://github.com/woowacourse/android-movie-theater/pull/27/commits/b06fd69f29b3784f93cdb4d328e4d5c7715a6881)

2023-05-08 06:31 UTC, DYGames commented on app/src/main/java/woowacourse/movie/view/activity/SeatSelectionActivity.kt
> +    override val presenter: SeatSelectionContract.Presenter = SeatSelectionPresenter(this)
Presenter의 생명주기를 View의 생명주기에 맞춰주었습니다.
Adapter를 View로 설정한 MVP에서는 Adapter가 Activity, Fragment의 생명주기에 맞춰 생성되므로 Adapter를 생성하는 시점에서 Presenter를 생성해주었습니다. [커밋](https://github.com/woowacourse/android-movie-theater/pull/27/commits/b06fd69f29b3784f93cdb4d328e4d5c7715a6881)

2023-05-08 07:23 UTC, DYGames commented on data/src/main/java/woowacourse/movie/data/dataSource/MovieDataSource.kt
> +        LocalDatabase.movieDBHelper?.selectAllMovies()?.toMutableList() ?: mutableListOf()
맨 처음에 MainActivity에서 LocalDatabase의 인스턴스를 생성해 Presenter -> Repository -> DataSource로 주입하는 방식으로 구현했었는데, 모든 객체의 생성자에 반복해서 같은 클래스를 요구하는 점이 어색하다고 생각해서 초기화 안됐음을 null로 알리는 nullable 객체로 만들고, 싱글톤으로 구현했었습니다.
다시 생각해보니 불변성, 테스트 가능성등 많은 요소들이 고려되지 않은 결정임을 이해하고 수정했습니다.
또한 고민이 생겼는데, 앱 전역에서 사용되는 SQLiteOpenHelper 같은 경우 View가 이동될때마다 close되고 open되는데, 이를 어떻게 관리해야하는게 좋을지 궁금합니다.
[커밋](https://github.com/woowacourse/android-movie-theater/pull/27/commits/b561fabcb7491b61cf4ccc624cc9c37e9877d0a8)

2023-05-08 08:35 UTC, DYGames commented on app/src/main/java/woowacourse/movie/presenter/MovieReservationPresenter.kt
> +package woowacourse.movie.presenter
화면별로 package를 재구성했습니다. 
여러 화면에서 공통적으로 사용되는 클래스에 대해선 어떻게 구성해야할지 궁금합니다.
[커밋](https://github.com/woowacourse/android-movie-theater/pull/27/commits/ae075115bece46a425801432bd52086c9acaf58b)

2023-05-08 08:50 UTC, DYGames commented on app/src/main/java/woowacourse/movie/contract/SeatSelectionContract.kt
> +        fun initActivity(movie: MovieViewData, reservationDetail: ReservationDetailViewData)
그런데 init 블럭에 view 로직을 호출하는 코드가 들어가니 presenter 테스트를 할 때 모든 테스트에 대해 init 블럭에서 호출하는 view 함수에 대한 answer를 설정해야 하는 문제가 발생했습니다.
제가 놓친 부분이 있을까요?

2023-05-08 08:54 UTC, DYGames commented
안녕하세요! 상세한 피드백 감사드립니다 ㅎ_ㅎ

피드백 적용하였고, 궁금한 점 코멘트 남겼습니다.

전체적인 구조에 대해 개선할 점이 보이시면 남겨주시면 감사하겠습니다!

감사합니다!

2023-05-08 16:33 UTC, galcyurio requested changes
피드백 잘 반영해주셨네요 👍️
질문해주신 부분들을 코멘트로 답변을 남겨두었습니다.
확인 후 다시 요청해주세요!

2023-05-08 16:33 UTC, galcyurio commented on data/src/main/java/woowacourse/movie/data/database/table/SQLTable.kt
> +interface SQLTable {
참고로 코틀린 공식 컨벤션과 다를 뿐 나쁜 네이밍은 아닙니다. 
iOS에서는 `SQLTable`이 공식 컨벤션으로 알고 있습니다. 🙂

또는 `SQLTable`은 금지하되 `TableSQL`과 같이 대문자가 이어지지 않는 경우는 오히려 읽기가 편하므로 허용하는 컨벤션도 있습니다.

2023-05-08 16:33 UTC, galcyurio commented on data/src/main/java/woowacourse/movie/data/database/MovieDBHelper.kt
> +class MovieDBHelper(context: Context) :
join을 하더라도 가져오는게 Movie이면 MovieDao로 짓습니다.

요즘은 DB를 사용할 때, ORM을 사용하는 경우가 많은데 특히나 Android의 경우에는 Room이라는 공식적으로 지원하는 ORM 라이브러리가 있습니다.
아래 Room 문서를 통해 대충 어떤 느낌인지만 보시면 될 것 같아요.
https://developer.android.com/training/data-storage/room/relationships#one-to-one

2023-05-08 16:33 UTC, galcyurio commented on data/src/main/java/woowacourse/movie/data/dataSource/MovieDataSource.kt
> +        LocalDatabase.movieDBHelper?.selectAllMovies()?.toMutableList() ?: mutableListOf()
SQLiteOpenHelper를 Application의 인스턴스 변수로 선언해보세요.

참고로 위 방법은 현재 미션을 위해 알려드린 방법이고 실제 업무에서는 의존성 주입 툴과 Room, androidx.startup 등을 활용합니다.

2023-05-08 16:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/view/activity/SeatSelectionActivity.kt
> +    override val presenter: SeatSelectionContract.Presenter = SeatSelectionPresenter(this)
Presenter는 `onCreate()`에 생성되는게 일반적입니다.

2023-05-08 16:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/contract/SeatSelectionContract.kt
> +        fun initActivity(movie: MovieViewData, reservationDetail: ReservationDetailViewData)
Mock 객체를 가지고 테스트할 때는 해당 Mock 객체의 함수가 호출되었을 때, 어떻게 되어야 하는지를 설정하지 않으면 에러가 발생합니다.
Mock 객체로서는 예상치 못했던 호출이 일어나는 것이므로 당연한 동작입니다.

MockK에서는 이러한 예상치 못했던 호출이 일어나도 에러가 나지 않도록 `mockk(relaxed = true)`를 통해 relaxed mock을 만들 수 있습니다.
설정해놓은 stubbing 코드들을 모두 제거하고 relaxed mock 객체를 사용해보세요.

2023-05-08 16:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/presenter/MovieReservationPresenter.kt
> +package woowacourse.movie.presenter
지금 해주신 것처럼 common, core 패키지 or 모듈을 만듭니다.
다만 이 클래스들도 여러가지가 생기면 별도의 feature 패키지로 분리합니다.

2023-05-08 17:50 UTC, DYGames commented on app/src/main/java/woowacourse/movie/contract/SeatSelectionContract.kt
> +        fun initActivity(movie: MovieViewData, reservationDetail: ReservationDetailViewData)
mock 객체를 relaxed로 생성하였습니다. 테스트 함수의 내용에 따라 mock 객체의 relaxed 옵션을 잘 조절해서 써야겠다고 생각했습니다.

2023-05-08 17:55 UTC, DYGames commented on app/src/main/java/woowacourse/movie/view/activity/SeatSelectionActivity.kt
> +    override val presenter: SeatSelectionContract.Presenter = SeatSelectionPresenter(this)
Activity -> Fragment -> Adapter의 구조에서 Adapter가 View인 MVP의 Presenter를 Fragment에서 Adapter 생성 시점에 해주었습니다. Adapter는 onCreate~() 콜백이 없어서 이렇게 구현했었습니다.

Activity가 View인 MVP의 Presenter의 경우 onCreate에서 생성해주었습니다.

2023-05-08 17:56 UTC, DYGames commented on data/src/main/java/woowacourse/movie/data/dataSource/MovieDataSource.kt
> +        LocalDatabase.movieDBHelper?.selectAllMovies()?.toMutableList() ?: mutableListOf()
MovieDao를 Application을 상속받는 App 클래스의 동반 객체에 두었습니다.

이를 최대한 상위 객체에서 주입해주도록 하였습니다. (Activity)

2023-05-08 17:59 UTC, DYGames commented
빠른 리뷰 감사드립니다 😊

피드백 반영하고 질문 사항 각 코멘트에 남겨두었습니다!

감사합니다!

2023-05-09 11:27 UTC, galcyurio approved these changes
한 가지 코멘트를 남겨두었으니 확인해주세요!
마지막까지 고생하셨습니다. 👏 👏

2023-05-09 11:27 UTC, galcyurio commented on data/src/main/java/woowacourse/movie/data/dataSource/MovieDataSource.kt
> +        LocalDatabase.movieDBHelper?.selectAllMovies()?.toMutableList() ?: mutableListOf()
클래스 변수가 아니라 인스턴스 변수에 두고 사용해야 합니다.
`App.movieDao`로 가져올 수 있기 때문에 여러 명이 협업을 하면 가장 상위 객체에서 주입한다는 의도가 깨지고 이상한 곳에서 사용할 수도 있습니다.
코드를 작성할 때는 항상 다른 개발자가 내 코드를 망치거나 의도를 깨지 않도록 주의해서 작성해야 합니다.

테스트할 때도 `App.movieDao` 코드가 실행되는 테스트 코드를 작성할 때, 항상 Application까지 초기화해주어야 합니다.

인스턴스 변수에 두고 의존성을 주입하는 방법을 겪어보도록 유도하는게 의도였습니다.

2023-05-09 11:27 UTC, galcyurio approved these changes
한 가지 코멘트를 남겨두었으니 확인해주세요!
마지막까지 고생하셨습니다. 👏 👏

2023-05-09 12:55 UTC, merged