[우기] 3, 4단계 영화 극장 선택 제출합니다.
woowacourse/android-movie-theater pull request #28
Opened 2023-05-06 06:41 UTC by boogi-woogi

2023-05-06 07:07 UTC, boogi-woogi commented on app/src/main/java/woowacourse/movie/ui/main/MainActivity.kt
> +
프래그먼트 인스턴스를 계속해서 생성하지 않기 위한 방법으로 구현해보았습니다!

2023-05-07 08:42 UTC, vagabond95 commented
> Fragment를 재사용하는 방법에 대해서 제가 구현한 코드에 대해 제리의 의견이 궁금합니다!

add 와 replace 의 차이, 그리고 addToBackstack() 처리를 했을 때 각각의 동작을 공부해보시면 스스로 해답을 내실 수 있을 것 같아요.
추가로 개인적인 생각을 남겨보면 fragment 를 포함하여 생명주기를 내가 컨트롤 할 수 있는 요소가 아닌 컴포넌트이 경우 재사용을 신중히 사용해야 한다는 입장입니다. 내부적으로 언제 재사용/재성성 등을 처리할 지 쉽게 알 수 없기 때문이이에요.

> onClick 이벤트가 발생했을 때 수행할 동작들은 바인딩을 해보았습니다. (커스텀한 BindingAdapter는 아직 사용하지 않았습니다.) BindingAdapter를 모든 view를 설정하는 코드에 대해서 적용하는지 그것이 아니라면 BindingAdapter를 사용해야하는 기준을 어떻게 잡아야 하는지 잘 모르겠습니다!

필요한 상황이 생기면 그 때 특정한 view 에 대해 사용하시면 되지 않을까 싶어요.
현재처럼 간단한 click 처리만 하는 경우 말씀하신 것처럼 별도 BindingAdapter 를 생성할 일이 없을 거 같습니다 ㅎㅎ

2023-05-07 08:43 UTC, vagabond95 requested changes
리뷰 전달이 조금 늦어졌습니다. 😿 

MVP 패턴으로의 전환은 크게 피드백 드릴 부분이 없었어요! 👍 
그 외에 구현에 대해 남긴 코멘트 확인 부탁드릴게요 :)

2023-05-07 08:43 UTC, vagabond95 commented on app/src/main/res/layout/activity_seat.xml
> +                android:onClick="@{() -> activity.showDialog()}"
activity 전체를 넘겨줄 필요가 있을까요?

2023-05-07 08:43 UTC, vagabond95 commented on app/src/main/res/layout/activity_seat.xml
> +                android:onClick="@{() -> activity.showDialog()}"
xml 내에서 클릭에 대한 처리를 

presenter 를 통하는 곳이 있고
activity 를 통하는 곳이 있는데요,

클릭 처리에 대한 역할은 동일한 레이어에 위임되어야하지 않을까요?

2023-05-07 08:43 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/util/SeatUtil.kt
> +fun String.toSeat(): Seat {
꼭 전역적으로 쓰여야하는 것이 아니라면

String 과 같이 다양한 곳에서 쓰일 수 있는 타입에 대한 확장함수는
접근 제한자를 통해 제한해보는 것이 어떨까요?

무분별하게 확장함수를 선언할 경우, string 변수를 접근할 때마다 무수히 많은 확장함수가 노출된다면 사용성이 떨어질 수 있을 것 같아요.

2023-05-07 08:43 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/ui/setting/SettingRepository.kt
> +interface SettingRepository {
Repository 를 인터페이스로 선언하여 느슨한 접근 👍

2023-05-07 08:43 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/ui/bookinghistory/BookingHistoryFragment.kt
> +        binding = FragmentBookingHistoryBinding.inflate(inflater)
fragment 는 객체의 생명주기와 view 의 생명주기가 각각 존재하게 되는데요,
view 가 언제 생성/파괴되는지 공부해보고

그에 따라 binding 객체가 어떻게 관리 되면 좋을지 공부해보면 좋을 것 같습니다~!

2023-05-07 08:43 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/ui/setting/SettingContract.kt
> +interface SettingContract {
contract 까지 잘 도입해주셨네요 👍

2023-05-07 08:43 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/ui/seat/SeatTableLayout.kt
> +        private val PURPLE = Color.parseColor("#8E13EF")
이러한 값도 string 과 같이 color resource 를 선언 후 재활용해보면 좋을 것 같아요~!

2023-05-07 08:43 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/ui/booking/BookingPresenter.kt
> +    override val movie: Movie = MovieRepository.getMovie(movieId)
singletone 으로 사용되더라도,
presenter 에서 주입받아 사용되도록 해보는 것은 어떨까요?

내부에서 바로 접근할 경우, 어떤 단점이 있을까요?

2023-05-07 08:43 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/ui/bookinghistory/BookingHistoryFragment.kt
> +    }
전반적으로 모든 activity, fragment 에서 검토 부탁드릴게요~!

presenter 에 주입하는 클래스들을 굳이 상태로 남겨둘 필요가 있을까요?

현재 당장은 사용하지 않더라도,
상태로 존재할 경우 view 에서 비즈니스 로직을 처리할 여지를 주는 것과 같아보여요.

2023-05-07 08:43 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/ui/home/TheaterRecyclerAdapter.kt
> +        val binding: TheaterItemBinding = TheaterItemBinding.inflate(layoutInflater, parent, false)
이 부분은 취향차이일 수 있지만,

추후에 viewHolder 의 binding 을 교체하거나 제거할 경우 ,Adapter 에 diff 가 생기지 않기 때문에
저같은 경우 inflate 하는 부분을 viewHolder 내부에서 companion object 함수를 통해 처리하는 것이 더 좋더라구요~!

2023-05-07 08:43 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/ui/home/HomePresenter.kt
> +        val mainData = MainModelHandler.getMainData()
이러한 hanlder 도 repository 감싸고, 주입받는 형태로 구현해보는 것은 어떨까요?

2023-05-08 15:54 UTC, vagabond95 requested changes
나름 꼼꼼히 봤는데, 크게 리뷰드릴 부분이 많이 없네요 😅 

view 와 presenter 에 대한 역할 구분을 미리 잘해주셨다는 생각이 듭니다.
간단한 코멘트만 남겼어요~!

2023-05-08 15:54 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/ui/booking/BookingActivity.kt
> +        bookingPresenter.initDateTimes()
현재는 문제가 없어보이는 부분이지만,

최초에 init 을 해줘야하는 것들이라면,
하나의 함수로 제공해보는 것은 어떨까요?

개별적으로 init 함수가 제공되는데, 
만약 이후에 init 에 대한 순서가 보장되어야 한다면, 수정 시 예기치 못한 버그를 유발할수도 있을 것 같습니다.

한번 들어간 코드는 큰 의미가 없어보여도, 보통 개별 히스토리가 있는 경우가 많아서 함부로 못건드리는 이유이기도 하구요 ㅎ
과할수도 있지만 저는 최대한 오해의 소지가 없도록 코딩하는 것이 좋다고 생각합니다~!

2023-05-08 15:54 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/ui/bookinghistory/BookingHistoryFragment.kt
> +        _binding = null
빼먹기 쉬운 부분인데, 추후에 크래시의 주범이 되는 녀석입니다. (제가 많이 당했습니다 😢 )

2023-05-08 15:54 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/ui/main/adapter/recyclerview/MovieViewHolder.kt
> +        with(binding) {
with 을 써주니 깔끔해졌네요 👍

2023-05-08 15:54 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/ui/completed/CompletedPresenter.kt
> +        val theaterName = TheaterRepository.getTheater(reservation.theaterId).name
개인적으로 궁금한 부분이었는데, repository 를 싱글턴으로 해주신 이유가 무엇인가요?

상태를 앱 전역에서 유지하기 위함이었을까요~?

2023-05-08 15:54 UTC, vagabond95 requested changes
나름 꼼꼼히 봤는데, 크게 리뷰드릴 부분이 많이 없네요 😅 

view 와 presenter 에 대한 역할 구분을 미리 잘해주셨다는 생각이 듭니다.
간단한 코멘트만 남겼어요~!

2023-05-09 13:48 UTC, boogi-woogi commented
안녕하세요 제리! 마지막까지 도움이 되는 리뷰를 해주셔서 정말 감사합니다!!

이번 미션으로 많은 것을 알게되어 정말 기쁩니다😀😀

계속해서 성장할 수 있도록 꾸준히 노력하겠습니다!

2023-05-10 02:03 UTC, vagabond95 approved these changes
미션 진행하시느라 고생 많으셨습니다~!

새로운 개념들이 대거 출현하여 쉽지 않으셨을 것 같은데,
큰 반향성에서 피드백 드릴 부분이 없을만큼 잘 해주셨어요.

해당 미션 과정이 좋은 밑거름이 되셨길 바랍니다 :)

2023-05-10 02:03 UTC, merged