[둘리] 3, 4단계 영화 극장 선택 제출합니다.
woowacourse/android-movie-theater pull request #31
Opened 2023-05-06 15:25 UTC by hyemdooly

안녕하세요, 리뷰어님!
이번 미션 요구사항이 대부분 처음 해보는 것들이라 까다로웠습니다.
MVP에서 Presenter의 역할이 어디까지인지 어렵네요.🥲 MVP를 고민하는데 가장 많은 시간을 사용한 것 같습니다.
이번 제출 코드에 도메인의 변경사항이 많아 핵심 변경 사항의 설명을 함께 첨부합니다!

## 코드 설명 - 도메인
### Schedule
- key : 극장 이름, List<LocalTime> : 극장이 영화를 상영하는 시간 리스트
Movie의 프로퍼티에 Schedule을 추가하여, 극장이 그 영화를 몇 시에 상영하는지 정보를 담았습니다.
### SeatInfo
- size : row, col
- gradeOfRow : 각 열의 등급 정보
Theater 클래스에 프로퍼티로 포함되어 있습니다.
액티비티에서 사용할 때는 색깔 정보도 필요하기에, toUiModel로 등급별 색깔 정보를 받아 변환할 수 있습니다.
### Theater
- name : 극장 이름, seatInfo : 좌석 정보, discountPolicies: 할인 정책 리스트
각 극장별로 할인 정책이나 좌석 정보가 달라지더라도 대응할 수 있도록 클래스를 생성하였습니다.
### ScreeningDateTimes
ReservationActivity에서 사용하는 클래스로, 기존 코드에서는 Movie에 포함되어 있었으나 극장에 따라 시간대가 달라지게 되면서 분리하였습니다.
극장 선택 후에 팩토리 함수를 사용하여 그 극장의 상영 시간에 맞는 LocalDate - List<LocalTime> Map을 생성합니다.
### System
- SeatSelectSystem : 좌석을 선택 후 결과(SelectResult)를 리턴하는 클래스
- PriceSystem : 기존 가격과 좌석 선택 결과를 받아 현재의 가격을 리턴하는 클래스
---
>사용자가 영화와 극장을 선택하면 ScreeningDateTimes를 생성하여 Spinner에 값을 세팅합니다.
정보를 입력한 후 좌석 선택 화면으로 넘어가면, ReservationOptions의 theaterName, TheaterRepository를 사용하여 극장의 정보를 가져옵니다. 이 정보를 이용하여 좌석을 그리고(뷰 동적 생성) SeatSelectSystem, PriceSystem을 생성합니다.
확인 버튼을 누르면 다이얼로그를 띄우고, 예매 완료 버튼을 클릭하면 DB에 저장 후 예매 완료 화면으로 이동합니다.
예매 완료 화면에서는 권한 체크, 허용되어있는 경우 알람을 세팅합니다.
---
## 질문
1. Presenter의 역할은 어디까지인지 어렵습니다. 특히 뷰의 값을 초기 세팅하는 것도 Presenter의 역할일까요?
Repository에서 데이터를 가져오는 것은 비즈니스 로직이라고 생각하여 분리했는데, 단순히 값을 가져오고 리턴하는 것은 Presenter의 역할이 아닌 것 같다는 느낌이 듭니다.
그렇다고 하여 View에서 각 요소마다 Set함수를 작성하자니 코드가 자잘하게 길어지는 것 같습니다.
2. 그동안 LocalDateTime Format이나, joinToString() 등 연산을 한 후에 뷰에 값을 세팅해주는 경우가 꽤 있었는데요. 데이터 바인딩을 적용하면서 이런 연산을 한 후에 세팅해야하는 경우 어떻게 해야하는지 잘 모르겠습니다. 간단한 String Format은 xml에서도 가능한데 말이죠...
지금 당장 생각나는 것은 각 뷰마다 ViewModel을 생성해준다, BindingAdapter를 생성하여 커스텀한다. 두 가지 방법인데요.
각 뷰마다 ViewModel을 일일히 작성해주자니 UiModel 클래스들의 존재 이유가 불명확해지는 것 같고, 커스텀 어댑터를 생성하자니 코드가 괜히 길어지는 것 같습니다.
이 외에는 방법이 없는걸까요? 보통 이런 경우에 어떻게 작성하나요?

2023-05-07 02:22 UTC, laco-dev requested changes
필요한 내용에 집중하기 위해서, 도메인 코드 부분의 리뷰는 제외했습니다.

데이터바인딩은 전반적으로 잘 적용을 해 주셨습니다.
MVP 아키텍처에 대해서는 화면마다 조금씩 다르게 구현이 된 것 같은데,  일관성 있게 정리하는 과정이 필요할 것으로 보입니다.

또한 MVP에서 잘못 적용된 개념과 방법 위주로 내용을 남겼습니다.

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/data/movie/MoviePosterRepository.kt
> +package woowacourse.movie.data.movie
MoviePosterRepository는 data 패키지에 위치하는 이유가 있을까요?

같은 로직이라면, MovieRepository와 비슷하게 사용해야 하지 않을까요?

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/data/setting/SettingDataManager.kt
> +}
Setting에 접근하는 것은 Repository가 아닌 DataManager로 사용된 이유는 무엇일까요?

만약, 설정에 접근하기 위해 서버 요청을 해야 한다면 이름이 바뀌어야 할까요?

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/data/theater/TheaterMockRepository.kt
> +        return theaters.find { it.name == name } ?: throw java.lang.IllegalArgumentException("존재하지 않는 상영관입니다.")
requireNotNull()을 사용 해보세요

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/data/theater/TheaterMockRepository.kt
> +    )
이 값들이 public으로 노출되어야 할까요?

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/util/MapExtension.kt
> +}
Map에 대해서 Index로 접근하는 것은 좋지 않은 방법입니다.
인덱스를 기반으로 값을 저장해야 했다면 Key 자체가 인덱스가 되어야 하지는 않을까 고민을 해야 합니다.

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/AlarmController.kt
> +    }
내부에서만 사용하는 것으로 바뀌었다면, 접근자를 private으로 변경하는 습관을 가져 주세요

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/mapper/PriceMapper.kt
> +}
UiModel이 String으로 변환되는 것에 사용하는 모두가 동의할까요?
이 문자열 포맷은 사용하는 곳에서 뷰에 그리기 위해 사용하는 것이지 않을까요?

DTO 성격으로 UiModel을 사용했다면, 1:1 관계로 변환이 가능해야 합니다.

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/mapper/MovieMapper.kt
> +fun Movie.toUiModel(@DrawableRes posterResourceId: Int): MovieUiModel = MovieUiModel(
`R.xxx`를 데이터에서 내려주지 못하기 때문에 이런 코드가 생기게 된 것으로 생각합니다.

개인적인 의견으로는, 굳이 이 내용 때문에 구조적으로 복잡하게 만드는 대신 변경을 최소화 하는 방법으로 만들어도 괜찮았다고 생각합니다.

만약, 그리기 위한 값을 서버에서 정상적으로 내려준다라고 가정했을 때, 현재 구현하신 코드와 아래 코드가 어떤 변경 과정을 거쳐야 하는지 생각 해 보시면 됩니다.

```kotlin
fun Movie.toUiModel(): MovieUiModel {
   val posterResourceId = posterResourceIdById[key]
   MovieUiModel(...)
}

private val posterResourceIdById: Map<String, Int> = mapOf(
   "영화 아이디" to R.drawable.xxx,
   ...
)
```

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/model/MovieUiModel.kt
> +    val schedule: Map<String, List<LocalTime>>,
Schedule이 가지고 있는 key값과 value가 어떤 것을 의미하는지는 PR 본문에만 남아있지 않을까요?
그러면 리뷰어랑 구현한 사람 외에 이 값이 무엇을 의미하는지 어떻게 알 수 있을까요?

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/model/SeatInfoUiModel.kt
> +class SeatInfoUiModel(val row: Int, val col: Int, val colorOfRow: Map<Int, Int>)
SeatUiModel과 SeatInfoUiModel 두 가지가 있습니다.

컬러값이 추가되면 Info인가요?
둘리가 생각하는 Info의 정의와 역할이 무엇일까요?

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/moviemain/MovieMainActivity.kt
> +                    val fragment = supportFragmentManager.findFragmentByTag(TAG_SETTING) as? SettingFragment ?: SettingFragment().also { addFragment(it, TAG_SETTING) }
현재 코드에서 필요한 값을 사용하려고 public으로 바꾸는 것 (X)
협력을 구현하기 위해 적절한 책임을 부여하는 것 (O)

레벨1에서 했던 경험을 다시 떠올려 주세요
프래그먼트를 가져오는 메시지를 전달해 스스로 할 수 있도록 만들어 보세요

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/moviemain/movielist/BottomSheetFragmentFactoryImpl.kt
> +class BottomSheetFragmentFactoryImpl(private val movie: MovieUiModel) : FragmentFactory() {
사용하신 것은 경험 해 본 것으로 생각하고, 아래 내용은 참고만 해주세요

프래그먼트 팩토리는 실무에서 잘 사용되는 개념은 아닙니다.
액티비티의 Intent로 넘기듯이, 프래그먼트의 Bundle로 넘기는 방법이 일반적으로 사용됩니다.

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/moviemain/movielist/MovieListAdapter.kt
> +                val view = LayoutInflater.from(parent.context).inflate(ListViewType.NORMAL_VIEWTYPE.id, parent, false)
이 반복되는 코드는 ItemViewHolder에서 할 수 있지 않을까요?

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/moviemain/movielist/MovieListContract.kt
> +}
MVP 패턴은, 프레젠터와 뷰가 같이 1:1 대응 관계를 가져야 합니다.

MVP 패턴에 대한 예제 코드를 다시 학습 해보세요

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/moviemain/movielist/MovieListContract.kt
> +        fun getMovieListData(): List<MovieUiModel>
뷰는 프레젠터에게 데이터를 요청하고 프레젠터는 결과를 받아 뷰에게 업데이트 요청을 합니다.
이 과정은 동기적으로 발생하지 않고 각 인터페이스에 따라 비동기적으로 요청이 이루어집니다.

즉, 프레젠터는 무언가를 **반환**하지 않습니다

```kotlin
// View
presenter.fetchMovieListData()

// Presenter
override fun fetchMovieListData() {
   val movieListData = some business logic
   view.showMovieListData(movieListData)
}

```

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/moviemain/setting/SettingContract.kt
> +        val requestPermissionLauncher: ActivityResultLauncher<String>
프레젠터에서 View 타입에 대해 위 함수를 사용할 수 있습니다.
이 값들이 View의 인터페이스로 존재하는 게 맞을까요?

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/moviemain/setting/SettingContract.kt
> +        fun onClick(isOn: Boolean)
프레젠터는 UI에 따라 인터페이스를 작성하지 않습니다.
클릭 과 같은 UI 이벤트를 호출하는 것이 아닌, 명시적으로 어떤 역할을 하는지 작성해야 합니다.

> 클릭이 알람을 바꾼다는 것을 사용하는 측이 어떻게 알까요?

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/moviemain/setting/SettingFragment.kt
> +        alarmController.cancelAlarms()
이 부분은 UI 에서만 해야하는 로직을 View 내에 잘 작성 해주셨습니다. 👍🏻

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/moviemain/setting/SettingFragment.kt
> +            setToggle(false)
예제를 그대로 옮겨서 사용할 때에는, 컨벤션과 나의 프로젝트 코드에 맞게 잘 고려 해주세요
스택오버플로우 같은곳에서 예제를 그대로 복붙하고 아무런 수정도 하지 않는 것과 똑같이 느껴집니다.

코틀린 컨벤션에 맞게 프로퍼티는 함수보다 위에 위치해야 합니다.
https://kotlinlang.org/docs/coding-conventions.html#class-layout

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/reservation/ReservationActivity.kt
> +        supportActionBar?.setDisplayHomeAsUpEnabled(true)
View에서 해야할 작업과 Presenter에서 해야할 작업이 합쳐져 있습니다.
프레젠터의 생성자로 Movie와 theaterName을 넘겨주면 어떤 차이가 있을까요?

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/reservation/ReservationPresenter.kt
> +
프레젠터에서 비즈니스 로직을 수행하고 결과를 뷰에 전파하도록 잘 작성 해주셨습니다.

다만 앞서 드린 의견처럼 클릭과 같은 이름을 사용하는 것이 아닌, 협력을 인터페이스로 잘 드러나도록 작성해야 합니다.

```
onMinusClick (X)
minusPeopleCount (O)
```

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/seatselection/SeatSelectionActivity.kt
> +        showToast(SELECT_WRONG_SEAT_MESSAGE)
인터페이스에서 함수를 작성할 때는 행동을 중심으로 작성합니다.
wrongInputToast(), maxSelectionToast()는 명사처럼 느껴지지 않을까요?

```kotlin
showMaxSelectionToast()
showWrongInputToast()
showToast(...)
```

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/seatselection/SeatSelectionContract.kt
> +        fun setDeselectionSeat(index: Int)
취향의 영역일 수는 있는데, 위와 같은 좌석 선택, 해제 이벤트를 setter처럼 작성하는게 맞을까? 라는 고민을 해보시면 좋습니다.

현재는 setter이기 때문에, 선택 해제되어 있는 좌석을 index로 set 한다로 볼 수 있습니다.
하지만 실제로는 setter로 들어온 좌석을 찾아서 "업데이트" 하는 순서로 이루어 집니다.

뷰가 setter로 받은 정보로 그대로 변경하는 개념이 아니라면, 이벤트 형태로 이름을 작성해도 좋습니다.

```kotlin
fun onSeatSelectedByIndex(index)
fun onSeatDeselectedByIndex(index)
```

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/seatselection/SeatSelectionContract.kt
> +        fun onReserveClick()
마찬가지로 click 대신, 명확하게 역할로 변경 해주세요

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/seatselection/SeatSelectionContract.kt
> +        val priceSystem: PriceSystem
이 정보가 View에게 노출될 필요가 있을까요?

필요한 값을 View의 인터페이스로 전달하면 되지 않을까요?

2023-05-07 02:22 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/seatselection/SeatSelectionPresenter.kt
> +    private fun rowColToIndex(row: Int, col: Int): Int = row * theater.seatInfo.size.col + col
Theater에게 각 행과 열에 맞는 좌석 정보를 가져오도록 메시지를 전달 해주세요

2023-05-07 02:22 UTC, laco-dev commented on app/src/test/java/moviemain/SettingPresenterTest.kt
> +        every { view.cancelAlarms() } just runs
mockk(relaxed = true)로 생성하면 just runs같은 동작을 생략할 수 있습니다.

2023-05-07 02:22 UTC, laco-dev commented on app/src/test/java/moviemain/SettingPresenterTest.kt
> +    }
초기값을 설정할 수 있는게 테스트의 목적일까요??

아니면 초기값은 False다를 확인하고 싶은게 테스트의 목적일까요?

2023-05-07 02:24 UTC, laco-dev commented
> 그동안 LocalDateTime Format이나, joinToString() 등 연산을 한 후에 뷰에 값을 세팅해주는 경우가 꽤 있었는데요. 데이터 바인딩을 적용하면서 이런 연산을 한 후에 세팅해야하는 경우 어떻게 해야하는지 잘 모르겠습니다. 간단한 String Format은 xml에서도 가능한데 말이죠...
지금 당장 생각나는 것은 각 뷰마다 ViewModel을 생성해준다, BindingAdapter를 생성하여 커스텀한다. 두 가지 방법인데요.
각 뷰마다 ViewModel을 일일히 작성해주자니 UiModel 클래스들의 존재 이유가 불명확해지는 것 같고, 커스텀 어댑터를 생성하자니 코드가 괜히 길어지는 것 같습니다.
이 외에는 방법이 없는걸까요? 보통 이런 경우에 어떻게 작성하나요?


1. UiModel에 작성한다 (이 경우 UI에 강한 커플링이 생깁니다)
2. object를 만들고, 데이터바인딩에서 import해서 사용한다
3. 로직을 View에서 처리하고, 실제 그리기 위한 값을 바인딩으로 넣어준다

2023-05-07 07:44 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/data/movie/MoviePosterRepository.kt
> +package woowacourse.movie.data.movie
domain보다 view의 관심사인 것 같아 app모듈에 위치하도록 했는데요, domain 모듈에 위치하는 것이 일관성있는 것 같아 옮겼습니다..!

2023-05-07 07:47 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/data/setting/SettingDataManager.kt
> +}
동일하게 Repository로 이름을 변경했습니다!

2023-05-07 08:15 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/view/model/SeatInfoUiModel.kt
> +class SeatInfoUiModel(val row: Int, val col: Int, val colorOfRow: Map<Int, Int>)
Seat은 좌석의 row, col, seatId를 담고, SeatInfo는 극장의 좌석 정보를 담습니다. (최대 몇 열인지, 몇 행인지, 각 열의 색깔은 무슨 색인지...)
명확하게 알 수 있도록 SeatInfo의 변수명을 변경하였습니다!

2023-05-07 08:33 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/view/moviemain/movielist/BottomSheetFragmentFactoryImpl.kt
> +class BottomSheetFragmentFactoryImpl(private val movie: MovieUiModel) : FragmentFactory() {
Fragment의 instantiate 함수가 deprecated되면서 FragmentFactory를 사용해야하는 것으로 알고 있는데 이것과는 관련 없는 내용인가요?

2023-05-07 10:03 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/view/moviemain/setting/SettingContract.kt
> +        val requestPermissionLauncher: ActivityResultLauncher<String>
presenter는 있어야하는 프로퍼티이기에 인터페이스로 존재하는 것이 좋다고 생각합니다!
하지만 requestPermissionLauncher는 존재하지 않아도 문제가 없어 삭제했습니다.

2023-05-08 04:14 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/view/mapper/PriceMapper.kt
> +}
1:1 관계로 변환이 가능해야한다는 말씀은 PriceUiModel을 생성해야한다는 말씀이신가요..!?
아니면 Int로 반환하는 것으로 충분할까요?

2023-05-08 04:18 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/view/model/MovieUiModel.kt
> +    val schedule: Map<String, List<LocalTime>>,
`typealias`를 사용하여 수정했습니다!

2023-05-08 04:19 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/data/theater/TheaterMockRepository.kt
> +    )
gradeColor는 UiModel로 변경 시 필요한 데이터라 유지하고, theaters만 private으로 변경하였습니다.

2023-05-08 05:09 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/view/reservation/ReservationActivity.kt
> +        supportActionBar?.setDisplayHomeAsUpEnabled(true)
프레젠터의 생성자로  movie, theaterName을 넘겨주니 onCreate의 코드가 더 간결해지고 보기 편해졌습니다.
Repository를 사용하여 데이터를 가져오지 않는 경우에도 프레젠터가 처음 데이터를 세팅해주는 것이 좋을까요?

2023-05-08 05:47 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/view/seatselection/SeatSelectionActivity.kt
> +        showToast(SELECT_WRONG_SEAT_MESSAGE)
showSeatMaxSelectionToast이 좋을까요, onSeatMaxSelection이 좋을까요..?
좌석 선택 시 4가지 경우 중 하나라 4가지 전부 네이밍을 통일해주면 좋을 것 같은데, 전자가 더 함수의 의도가 확실해보여서 고민했습니다!

2023-05-08 07:42 UTC, hyemdooly commented on app/src/test/java/moviemain/SettingPresenterTest.kt
> +    }
세팅값을 가져와서 검사하도록 수정했습니다!

2023-05-08 07:48 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/view/mapper/MovieMapper.kt
> +fun Movie.toUiModel(@DrawableRes posterResourceId: Int): MovieUiModel = MovieUiModel(
toUiModel 내부에서 찾아서 매핑해주도록 간단하게 수정했는데요, 만약 서버에서 내려준다면 Repository를 참조해야하지 않을까 생각됩니다!
아니면 처음부터 서버에서 그리기 위한 값을 포함하여 내려줄 수도 있을 것 같습니다.

2023-05-08 08:51 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/view/seatselection/SeatSelectionPresenter.kt
> +    private fun rowColToIndex(row: Int, col: Int): Int = row * theater.seatInfo.size.col + col
rowColToIndex는 클릭 시 view에서 index로 뷰들의 변경 사항을 처리하고 있기때문에 필요한 함수입니다.
index로 처리하지 않고 row, col로 처리하도록 하려면 액티비티의 코드 변경이 필요하나 시간이 부족해 하지 못했습니다.

SeatUiModel에 color을 추가했습니다. 액티비티 코드를 프레젠터로 일부 이동시켜, 프레젠터에서 theater의 좌석 열, 행만큼 뷰 생성을 반복하도록 했습니다.
또한, 좌석 생성 시 프레젠터에서 해당 열에 맞는 color를 주입하여 넣을 수 있도록 코드를 수정했습니다!
theater에서는 색깔 정보를 알려줄 수 없다고 판단하여(뷰의 관심사이기 때문에) 따로 정의하여 주입했습니다..!

2023-05-08 12:09 UTC, laco-dev requested changes
피드백 반영 고생하셨습니다.

몇 가지 간단한 의견을 추가로 남겨두었습니다. 💪🏻

2023-05-08 12:09 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/data/theater/TheaterMockRepository.kt
> +        requireNotNull(theater) { "존재하지 않는 상영관입니다." }
requireNotNull이 무엇을 반환하는지 확인 해보세요

2023-05-08 12:09 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/mapper/PriceMapper.kt
> +    return price
> 1:1 관계로 변환이 가능해야한다는 말씀은 PriceUiModel을 생성해야한다는 말씀이신가요..!?
아니면 Int로 반환하는 것으로 충분할까요?

Price가 UiModel로 변환되는데 왜 Int가 나오지? 라는 것에 다른 개발자가 봐도 납득이 될까요?

2023-05-08 12:09 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/model/SeatInfoUiModel.kt
> +data class SeatInfoUiModel(val maxRow: Int, val maxCol: Int, val colorOfRow: Map<row, colorId>)
제가 의도한 질문은... 왜 Info가 붙어야 하는가? 에 대한 내용입니다.

단순히 Seat에서 데이터를 더 가지고 있으면 Info인가요?
Info가 너무 범용적이라고 생각하지 않나요?

또한 제가 읽기에는 Seat와 SeatInfo가 무슨차이가 있는지 모르겠습니다.

2023-05-08 12:09 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/moviemain/movielist/MovieListFragment.kt
> +    override var presenter: MovieListContract.Presenter = MovieListPresenter(this, MovieMockRepository)
Presenter를 생성자 시점에 만들 수 없는 경우가 대부분입니다.
위 코드에서 Context를 참조 해보세요

2023-05-08 12:09 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/moviemain/setting/SettingFragment.kt
> +        }
> Fragment의 instantiate 함수가 deprecated되면서 FragmentFactory를 사용해야하는 것으로 알고 있는데 이것과는 관련 없는 내용인가요?

팩토리를 이용하는 것과 프래그먼트의 Bundle에 담아 전달하는 것이 차이가 있을수도 없을수도 있습니다.

프래그먼트에 값을 넘겨주는 방법을 찾아 보시면 될 것 같습니다. 팩토리 말고!

2023-05-08 12:09 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/reservation/ReservationContract.kt
> +        fun setViewData(movie: MovieUiModel, theaterName: String)
setViewData(...) 라는 이름으로 생각이 든 점은,
앞으로 View의 UI가 변경되면 항상 setViewData()의 파라미터가 늘어나면 되는거 아닌가? 라는 생각으로 이어지네요

2023-05-08 12:09 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/seatselection/SeatSelectionPresenter.kt
> +    private fun rowColToIndex(row: Int, col: Int): Int = row * theater.seatInfo.size.col + col
이상하군요.. 뷰의 관심사인데 전부 프레젠터가 가지고 있네요. 🤔

2023-05-08 12:09 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/moviemain/movielist/MovieListContract.kt
> +        var presenter: Presenter
> presenter는 있어야하는 프로퍼티이기에 인터페이스로 존재하는 것이 좋다고 생각합니다!
하지만 requestPermissionLauncher는 존재하지 않아도 문제가 없어 삭제했습니다.

있어야 하는 프로퍼티는 맞는데 인터페이스에 포함되어야 하는게 맞나요?
```kotlin
// Presenter
view.presenter // 이렇게 호출해도 되는건가요?
```

2023-05-08 12:09 UTC, laco-dev requested changes
피드백 반영 고생하셨습니다.

몇 가지 간단한 의견을 추가로 남겨두었습니다. 💪🏻

2023-05-08 13:11 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/view/mapper/PriceMapper.kt
> +    return price
UiModel을 따로 만들어주지 않았으므로 납득이 안될 코드였네요..!
생각해보니 DecimalFormat을 사용하기 위해 만든 Mapper였는데 네이밍이 먼저 잘못되었고, 지금은 프레젠터에서 Price 도메인 모델의 Int값을 뷰에 전달하고 있기에 삭제해도 되는 확장함수 같습니다!

2023-05-08 13:11 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/data/theater/TheaterMockRepository.kt
> +        requireNotNull(theater) { "존재하지 않는 상영관입니다." }
null이 아니면 value를, null이면 throw IllegalException을 하는 것을 확인하고 수정했습니다!
require과 비슷한 로직인 줄 알았는데 조금 다른 것이었네요😅

2023-05-08 13:20 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/view/moviemain/movielist/MovieListFragment.kt
> +    override var presenter: MovieListContract.Presenter = MovieListPresenter(this, MovieMockRepository)
Activity 처음 다룰 때 비슷한 내용을 봤었는데 잊어버리고 있었네요..!! onViewCreated로 초기화 코드를 이동했습니다!

2023-05-08 13:21 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/view/moviemain/movielist/MovieListContract.kt
> +        var presenter: Presenter
View에서 presenter를 사용하도록 강제하고 싶었는데 view.presenter로 호출을 할 수 있다는 생각을 못했습니다. 수정했습니다!

2023-05-09 04:50 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/view/moviemain/setting/SettingFragment.kt
> +        }
Bundle로 값을 넘겨주는 방법으로 적용해보았습니다!

2023-05-09 13:59 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/view/model/SeatInfoUiModel.kt
> +data class SeatInfoUiModel(val maxRow: Int, val maxCol: Int, val colorOfRow: Map<row, colorId>)
Info라는 네이밍이 애매모호한 것 같습니다. Theater가 가지고 있는게 더 명확해보여서 프로퍼티를 이동시켰습니다!

2023-05-09 15:01 UTC, laco-dev approved these changes
이번 미션도 고생 많으셨습니다.
지금까지 잘 해주신 것 처럼, 선택과 집중을 통해 많은 것을 얻어 가셨으면 좋겠습니다.

2023-05-09 15:01 UTC, merged