[멘델] 3, 4단계 영화 극장 선택 제출합니다.
woowacourse/android-movie-theater pull request #36
Opened 2023-05-07 14:12 UTC by rhthrhrl0

# 주요 변경점
MVP적용, 프레젠터 테스트 코드 작성, 예매 내역 로컬 저장소 추가, 데이터바인딩 적용, 극장 선택 기능 추가

### MVP적용
뷰의 모든 이벤트들(클릭 혹은 브로드캐스트 리시버의 이벤트 수신 등)이 발생하면 모두 프레젠터를 거쳐서 프레젠터의 판단 하에 뷰 로직을 실행하도록 구성했습니다.

### 프레젠터 테스트 코드
모든 레포지토리를 추상화 시켜서 테스트 가능한 mock레포지토리 객체를 만들 수 있도록 구성했습니다. 레포지토리 인터페이스는 도메인 모듈에 위치시켰고, 레포지토리 구현체는 앱 모듈에 위치시켰습니다. 

### 예매 내역 로컬 저장소 추가
SQLiteOpenHelper를 상속받은 ReservationTicketsDao 를 만들어서 예매 테이블과 예매 좌석 테이블 두 개를 만들었습니다. 여기서 이 두 테이블은 reservationId로 조인 시켜서 사용합니다.

### 데이터바인딩 적용
라이브 데이터나 Observable 없이, 순수한 데이터바인딩 기능만 사용했습니다. 때문에 주로 뷰가 초기화되는 단계에서 xml과 데이터를 이어주는데 사용하거나, 인자가 없거나 불변 인자를 받아서 실행되는 메소드들만 xml의 onClick 속성에서 연결해서 사용하고 있습니다.
추가적으로, xml에서 import를 사용해도 정의하기 힘들다고 생각되는 속성 값들은 BindingAdapter를 정의해서 사용했습니다. 

### 극장 선택 기능
극장 선택을 위한 바텀시트는 **바텀 시트 프래그먼트**를 사용했습니다. 이때, TheaterBottomSheetFragment에서 선택한 극장에 대한 정보는 setFragmentResult로 MovieListFragement에게 넘겨주고 있습니다.

## 말씀드리고 싶은 기타 내용들
영화와 극장과 관련된 정보는 별도의 로컬 저장소에서 관리하지 않고, 도메인 모듈에 위치한 데이터 소스파일에 선언해서 사용하고 있습니다. 
개인적으로 BindingAdapter들을 알맞은 용도로 정의한 것인지 잘 모르겠습니다. xml 수준에서 끝낼 수 있는 더 좋은 방법이 있는데 제가 못찾고 바로 BindingAdapter를 선언한 것은 아닌지 전체적으로 확인 받고 싶습니다. 
바쁘신 와중에도 리뷰 해주셔서 감사합니다. 리뷰 잘부탁드립니다!!

2023-05-08 07:43 UTC, vagabond95 commented
BindingAdapter -> 코드상에서 따로 리뷰 드렸습니다.

Usecase ->
우선, UseCase 를 도입하는 목적이 무엇인지에 대해 생각해보면 좋을 것 같아요.

usecase 를 사용함으로써 좀 더 의존성을 느슨하게 가져가고 계층화시킬 수 있지만, trade off 요소로 구조가 과하게 복잡해진다는 단점이 있습니다. 따라서 저는 현재 프로젝트 수준에서는 사실 필요가 없는 계층이라는 생각이 들어요.

usecase 가 의의가 있으려면, usecase 로 추상화한 비즈니스 로직이 재사용되어야 할텐데 현재는 presenter 를 분리한 느낌에 가깝다는 느낌은 있습니다.

하지만 위 내용과 별개로 usecase 로 분리하는 과정이 쉽지 않으셨을 것이고, 분리를 해주심으로써 MVP 로의 전환이 좀 더 수월하게 된 것으로 보여요! 의미없는 구현이라고 생각하지는 않습니다 :)

2023-05-08 07:44 UTC, vagabond95 requested changes
MVP 패턴을 전반적으로 깔끔하게 잘 적용해주셨네요 👍 

제가 생각한 구현 방향에서 크게 벗어난 부분이 없었습니다.

질문 주신 내용을 포함하여 몇가지 고민해볼 부분에 대해 코멘트 남겼는데 확인 부탁드려요~!

2023-05-08 07:44 UTC, vagabond95 commented on app/src/main/res/layout/activity_movie_detail.xml
> +                    android:text="@{DateTimeFormatters.INSTANCE.convertToDateTildeDate(context,theaterMovie.movie.startDate,theaterMovie.movie.endDate)}"
이러한 코드는 presenter 레벨에서 처리해주는 것이 어떨까요?

xml 에 로직이 들어가는 것은 유지보수 측면에서 지양해야할 것 같아요.

2023-05-08 07:44 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/feature/setting/SettingFragment.kt
> +        _binding = null
binding null 처리는 빼먹기 쉬운 부분인데, 잘 처리해주셨네요 👍

2023-05-08 07:44 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/data/AlarmSettingRepositoryImpl.kt
> +class AlarmSettingRepositoryImpl(context: Context) : AlarmSettingRepository {
preference 를 특정한 도메인마다 만들어주시는 것으로 보이는데요.

도메인이 생길때마다 preference 를 만들어주는 것과, 공용으로 하나의 preference 를 통해 처리하는 방식 
각각의 장단점은 무엇이고 멘델은 어떤 것을 선택하고 싶으신지 궁금합니다.

2023-05-08 07:44 UTC, vagabond95 commented on app/src/main/res/layout-land/activity_seat_select.xml
> +        <TableLayout
현재 단계에서 중요한 부분은 아니지만,
table row 를 동적으로 추가하고 관리하는 커스텀 뷰를 추가해줘도 좋을 것 같아요.

여기서 좌석수 / UI 에 대한 변경사항이 발생할 때마다 모든 xml 컴포넌트에 적용을 시켜줘야할텐데,
이는 너무 비효율적인 방식인 것 같아요.

2023-05-08 07:44 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/feature/seatSelect/SeatSelectPresenter.kt
> +    }
요런 비즈니스 로직들, presenter 에서 처리해주시는 것 좋습니다 ~! 👍 👍

2023-05-08 07:44 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/feature/seatSelect/SeatSelectActivity.kt
> +    private lateinit var reservationState: SelectReservationState
reservationState 는 presenter 에 넘겨만 주고, activity 에서는 상태를 제거해보는 것은 어떨까요?

모델을 activity / presenter 에서 모두 접근 가능할 경우 비즈니스 로직의 구현이 분산될 여지가 있을 것 같아요.

2023-05-08 07:44 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/feature/seatSelect/SeatSelectActivity.kt
> +    }
매번 view 를 순회하는 것은 비효율적으로 보이는데, 좀 더 효율적으로 개선해볼 수 있을까요?

2023-05-08 07:44 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/feature/movieList/bottomSheet/TheaterBottomSheetFragment.kt
> +    override fun setTheaterAdapter(theaters: List<TheaterItemModel>) {
구체적으로 adapter 라는 정보를 드러낼 필요가 없을 것 같습니다.

함수 네이밍에 무슨 일을 수행하는지만 표현하는 것이 좋은 이유는,
구체적인 구현 방법은 쉽게 변경되지만 무슨 일을 수행하는지 (=역할)는 변경되지 않기 때문입니다.

2023-05-08 07:44 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/feature/movieList/bottomSheet/TheaterBottomSheetFragment.kt
> +        dismiss()
dismiss 는 별도 함수로 분리하여 처리해보는 것은 어떨까요?

select 라는 역할을 수행했는데, dialog 가 종료될 것이라고 쉽게 유추하기 어려울 것 같습니다.

2023-05-08 07:44 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/feature/movieList/MoviesPresenter.kt
> +                    it.asPresentation().toItemModel { movieState ->
asPresentation() 과 toItemModel 을 하나로 통합해도 괜찮지 않을까요?

itemModel 이 곧 presentation layer 에서 사용되는 모델이니까요 ㅎㅎ
mapping 이 중복되는 느낌을 받았습니다.

2023-05-08 07:44 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/feature/movieList/MovieListContract.kt
> +        fun loadMovieAndAdvItemList()
네이밍에 and 가 들어가는 것은 최대한 지양해보는 것이 어떨까요?

함수가 너무 구체적인 구현정보를 드러내고 있거나, 하나 이상의 역할을 하고 있을 가능성이 높습니다.

2023-05-08 07:44 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/feature/common/adapter/CommonAdapter.kt
> +class CommonAdapter(
CommonViewHolder 까지는 좋은 접근이었으나,
Adapter 는 조금 고민해볼 필요가 있을 거 같아요.

앱 전체에서 사용되는 viewholder 를 한곳에 모아서 처리하는 것으로 보이는데,
앱 사이즈가 커질수록 기하급수적으로 비대해지고

무엇보다 하나 이상의 도메인에 대해 처리하고 있기 때문에 좋지 않은 구조라고 생각됩니다.

2023-05-08 07:44 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/feature/movieList/viewHolder/MovieViewHolder.kt
> +    view.setImageResource(id)
해당 binding adapter 를 `제외하고` 
나머지 binding adapter 의 경우 지양해야될 사용 방식인 것 같아요.

특정한 모델에 대한 bindingAdapter 를 만들기 시작하면 너무 많은 binding adapter 가 만들어질 것이고,
더 큰 문제는 코드가 파편화 되어 변경사항이 생길 때 어느 코드를 봐야할지 감을 잡기가 어려울 것 같습니다.

2023-05-09 17:32 UTC, rhthrhrl0 commented on app/src/main/res/layout-land/activity_seat_select.xml
> +        <TableLayout
좋은 피드백 주셔서 감사합니다!! 해당 내용은 현재 진행중인 미션을 진행하는데 있어서.. 시간적으로 힘들것 같다고 판단이 되어서 이번 미션에서는 순위를 조금 미루고 싶습니다... 꼭 기회가 될때 공부해도록 하겠습니다. 학습에 도움이 되는 피드백 주셔서 정말 감사합니다!!

2023-05-13 17:51 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/movie/feature/seatSelect/SeatSelectActivity.kt
> +    }
by lazy를 활용해서 최초 1회에만 뷰들을 순회해서 그 중 좌석 뷰들만 리스트로 관리하는 프로퍼티로 만들었습니다

2023-05-14 11:48 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/movie/data/AlarmSettingRepositoryImpl.kt
> +class AlarmSettingRepositoryImpl(context: Context) : AlarmSettingRepository {
3.4단계를 구현하려고 기존 코드를 리팩토링 하면서, "레포지토리 구현체 안에 쉐어드 프리펀런스를 감춰야지" 라는 생각으로 처음에 잘못 접근하고 이렇게 만들었습니다. 생각해보니 sharedPreference 객체 자체가 레포지토리 구현체 안에 있어야 하는 것이 중요한게 아니였던 것 같습니다. preference 객체는 앱 어디에서나 쉽게 접근하기 위해 한번만 초기화되면 될 것 같다고 생각합니다. 안그렇다면, 컨텍스트가 없는 환경에서는 사용하지 못하기 때문입니다. 혹시 이 외에 양쪽(한번만 preference 초기화 or 매번 preference 생성)에 대한 장단점이 존재할까요??

2023-05-14 11:54 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/movie/feature/movieList/MoviesPresenter.kt
> +                    it.asPresentation().toItemModel { movieState ->
해당 문제에 대해서 깊게 고민해보았으나 더 나은 방법이 생각나질 않습니다.
도메인모델로부터 ui모델로 변환되는 과정에서 얻어낸 데이터 정보들과  어댑터에 붙기 위한 클릭 람다 요소들을 분리 하고 싶어서 uiModel과 ItemModel 을 분리했습니다.  사실 ItemModel이라는 말도 제가 적당히 붙인 것이라서 이게 적절한 것인지 모르겠습니다.  

현업에서는 어댑터 안에 들어갈 아이템들의 클릭 람다들을 어떻게 '어댑터 -> 뷰홀더' 를 거쳐 전달 시켜주나요?? 어댑터의 생성자에 이 어댑터에 들어올 수 있는 모든 아이템들의 람다들을 전달해주나요? 아니면, 아이템 별로 자신의 클릭 람다들을 관리하도록 하나요??

2023-05-14 12:25 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/movie/feature/common/adapter/CommonAdapter.kt
> +class CommonAdapter(
분리시켰습니다!! 이렇게 해도 되나 궁금했었는데 지적해주셔서 감사합니다!

2023-05-14 12:43 UTC, rhthrhrl0 commented
늦게 제출해서 죄송합니다 ㅠㅠ 현재 미션과 병행하려다보니 쉽지 않았던 것 같습니다. 답변 주신 내용들에 대해서 최대한 고민을 해보고 싶어서 더 미뤘던 것도 없지 않아 있었는데, 고민을 더 하고 서칭을 더 한다고 이렇다 할 결론이 나오지 않았습니다. 이번 미션 내내 친절하게 제 긴 질문들에 답변해주셔서 감사합니다!!

2023-05-15 10:33 UTC, vagabond95 commented on app/src/main/res/layout-land/activity_seat_select.xml
> +        <TableLayout
넵 너무 부담갖지 않으셔도 됩니다 :)

2023-05-15 10:50 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/feature/movieList/MoviesPresenter.kt
> +                    it.asPresentation().toItemModel { movieState ->
컨텍스트가 2가지 인것 같아서, 각각 답변드려보겠습니다.

1. asPresentation() 과 toItemModel 을 하나로 합쳐도 되지 않을까?

해당 코멘트를 드렸던 이유는, layer 관점에서 presentaion model 과 item model 모두 ui 레이어에 속하기 때문입니다.
물론, item model 에 대한 매핑 과정을 추가로 두어도 잘못된 것은 아니지만, model 의 layer 를 가져감에 있어서 일관된 규칙이 있으면  좋지 않을까하여 질문드렸습니다.

2. 어댑터 안에 들어갈 아이템들의 클릭 람다들을 어떻게 '어댑터 -> 뷰홀더' 를 거쳐 전달 시켜주나요??
정답은 없을 것 같습니다.

어뎁터 레벨에서 람다를 받는다면, viewModel 에서 item 클릭에 대한 함수를 open 하고 itemModel 을 전달받는 식으로 처리가 될 것으로 보이고

아이템 별로 클릭에 대한 람다를 전달해주는 것도 가능하고 틀린 구현이라고 할 수는 없습니다.
다만, 아이템 별로 람다를 전달 했을 때 람다가 외부 변수를 참조하고 있을 경우 메모리 상으로는 조금더 비효율적인 코드라고 볼 수는 있겠습니다. :)

2023-05-15 10:52 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/data/AlarmSettingRepositoryImpl.kt
> +class AlarmSettingRepositoryImpl(context: Context) : AlarmSettingRepository {
제가 남겨드린 코멘트의 내용이 모호했네요 ^^;

저는 객체의 초기화 관점이 아닌, 클래스의 분리 관점으로 말씀드린 것이긴 합니다!
즉, A 도메인 preference, B 도메인 preference 요렇게 도메인 별로 preference 를 나눌 것인지
아니면 단일한 preference 에서 모두 관리할 것인지에 대한 생각이 궁금했어요!

2023-05-15 10:53 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/data/AlarmSettingRepositoryImpl.kt
> +class AlarmSettingRepositoryImpl(context: Context) : AlarmSettingRepository {
초기화 방식의 경우,
상태의 생명주기에 따라 고려해주시면 될 것 같습니다.

해당 클래스에서 다루는 상태가 전역적으로 유지되어야 하는지, 아니면 매번 생성시마다 다른 상태를 가질 수 있는지에 따라 달라질 것 같습니다.

2023-05-15 11:01 UTC, vagabond95 approved these changes
Usecase 를 깔끔하게 도입해주셔서, MVP 로 마이그레이션 하는 과정에서 도메인 로직들이 쉽게 이동될 수 있었던 점이 기억에 많이 남았습니다.

적지 않은 요구사항이 있었던 미션이셨을텐데, 고생 많으셨어요! 
질문 주신 내용에 대한 답변 및 추가 구현에 대한 코멘트는 다음 미션 진행시 참고 부탁드립니다.
고생 많으셨습니다!

2023-05-15 11:01 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/feature/confirm/ReservationConfirmActivity.kt
> +            DecimalFormatters.convertToMoneyFormat(tickets.totalDiscountedMoneyState)
이러한 포매팅은 activity 와 presenter 중 어디서 처리하면 변경에 더 용이할까요?

2023-05-15 11:01 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/feature/movieList/MoviesPresenter.kt
> +            val allowAdvMaxCount: Int = movies.size / 3
3 과 같은 값은 상수로 관리해주면 더 좋을 것 같아요.

중요한 요구사항인데, 숫자로 하드코딩 되어있으면 의미를 알아채기 힘들 것 같아요.

2023-05-15 11:01 UTC, vagabond95 approved these changes
Usecase 를 깔끔하게 도입해주셔서, MVP 로 마이그레이션 하는 과정에서 도메인 로직들이 쉽게 이동될 수 있었던 점이 기억에 많이 남았습니다.

적지 않은 요구사항이 있었던 미션이셨을텐데, 고생 많으셨어요! 
질문 주신 내용에 대한 답변 및 추가 구현에 대한 코멘트는 다음 미션 진행시 참고 부탁드립니다.
고생 많으셨습니다!

2023-05-15 11:01 UTC, merged

2023-05-15 11:21 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/movie/feature/movieList/MoviesPresenter.kt
> +                    it.asPresentation().toItemModel { movieState ->
외부변수 캐칭 람다에 대한 내용이였군요... 코틀린 인 액션 책에서 읽고 이러한 단점이 있구나 라고 읽고 넘어갔던 적이 있는데, 실제로는 사용하면서 생각하지 않았었습니다. 앞으로는 람다 사용 시 메모리 측면도 고려하도록 하겠습니다. 덕분에 제 기존 방식의 단점이 확 와닿았습니다. 친절한 답변 감사합니다!

2023-05-15 11:25 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/movie/feature/confirm/ReservationConfirmActivity.kt
> +            DecimalFormatters.convertToMoneyFormat(tickets.totalDiscountedMoneyState)
프레젠터가 비즈니스 로직을 담고 있기 때문에, 프레젠터에서 변환해서 딱 변경할 String만 뷰(액티비티)에게 넘겨주는 것이 맞는 것 같습니다 :)

2023-05-15 11:29 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/movie/data/AlarmSettingRepositoryImpl.kt
> +class AlarmSettingRepositoryImpl(context: Context) : AlarmSettingRepository {
아하...질문하신 내용을 이해했습니다. 저는 도메인별로 preference를 나누는 것이 파일명이 애초에 다르기 때문에 추후에 혼동되지 않을 것 같다고 생각되는데, 팀원들과 얘기를 나눠서 결정해야 할 것 같습니다!!