[멧돼지] 3, 4단계 영화 극장 선택 제출합니다.
woowacourse/android-movie-theater pull request #37
Opened 2023-05-07 15:22 UTC by 2chang5

이번 미션 정말 집중하고 연휴 내내 매달려서 열중했던것 같습니다. 
현재 코드의 문제점도 많이 보이고 데이터 바인딩의 경우 4단계 미션에서 새롭게 작성한 코드만 적용해보았습니다. 
(데이터 바인딩보다는 MVP와 presenter 테스트에 좀더 집중해 보려고했습니다.)

MVP 형태로 도메인을 액티비티로 부터 뜯어내고 Presenter를 테스트하기 좋은 형태로 만들려고 노력해봤습니다.
또한 Presneter test에 집중해 보았는데 맞는 형태로 했는지 잘모르겠습니다ㅠㅠ. 
그리고 지난번에 조언해주신대로 미리 서버와 통신한다는 가정하에 추상화를 한번거쳐서 더미데이터들을 배치해서 나중에 변경에 쉽게 대응할수있게 했습니다. ( 레포지토리와 데이터소스라고 네이밍하고 사용하면, 제대로 알고 쓰라고 혼날것 같아서 추상화를 한단계만 거쳐서 비슷한 역할을 할수있도록 해보았습니다.)

이번 미션을 진행하며 어려운 부분이 3가지 있었는데 이부분은 어떻게 대응해야 현명할지 궁금합니다.

1.Ticket객체에 Id 값 부여
이것이 정상적인 앱이라면 서버와 통신해서 서버에서 Ticket을 발급하고 거기서 auto Increment 같은 것들로 Id 값을 중복되지않도록 관리해야 한다고 생각합니다. 하지만 현재는 서버가 없기 때문에 Ticket의 고유 값을 갖기위해 코틀린 자체에서 인스턴스를 생성할때마다 auto Increment 같이 ID 값을 부여할수 있는 방법을 찾아보았으니 찾지 못하였습니다.
그래서 local저장소(sharedPreference사용)에 인스턴스를 생성할때마다 1씩 늘려서 Id값을 부여하도록 했습니다.
이에 따라 TicketModle을 사용하는 모든 곳에서 context를 받아야했기 때문에 안드로이드 의존성이 강하게 발생하였습니다.
이럴때 코틀린 자체에서 Id값을 부여하거나 안드로이드와 관련없이 순수 자바 코틀린 모듈에서도 저장소를 관리 유지할수있는 방법이 있을까요?  
(물론 안드로이드가 저장공간을 갖고있는건데 안드로이드없이 저장공간을 확보한다는게 말이 안된다고 생각합니다.)

2.잘못된 라이브러리 선택과 잘못된 저장소 선택
이번 미션에서 저장소에 많은 힘을 쓰고싶지않아서 예매 영화내역을 sharedPreference 에다가 저장하려고 시도했고 객체의 리스트를 집어넣기위해 Json으로 파싱해서 집어넣고 그것을 다시 직렬화 해서 사용하려 시도하였습니다.
그러면서 많은 뻘짓을 했고 왜 간단한 데이터 저장만 sharedPreference를 사용하고 복잡한것들은 다른것을 사용하는지 꺠달았습니다.
근데 이때 직렬화를 위해서 기존에 주로 사용하던 Gson 이 아닌 kotlinx serialization 을 사용하게 되었습니다.
kotlinx serialization을 사용하게 된 이유는 코틀린에 맞춰서 몇가지 기능들이 더 제공된다고 해서 사용해봤는데
localDateTime도 제대로 처리못하는것을 보고 충격과 공포와함께 그냥 Gson 쓸걸 이라는 생각을 50000 번 했습니다.
이럴때 항상 드는 고민이 라이브러리의 선택기준이 참애매하고 생각합니다.
최근에 나온 새로운 기능을 탑재한 라이브러리랑 검증된 라이브러리중 리뷰어님은 어떤기준에 따라 어떤걸 사용하시는지 궁금합니다.

3.presenter 의 너무많은 프로퍼티
presenter를 만들다보니 생성자를 통해서 주입받아야할게 너무많고 (Dependency Injection을 통해 테스트 가능성을 열기위해)
그러다보니 presneter가 갖고있는 프로퍼티가 진짜 너무 많아졌습니다. level1 을 진행하며 프로퍼티가 너무많은것은 안좋다고 배웠기에 
줄여야하나 생각해보았지만 사실 이것은 어쩔수없는것 아닌가? 라는생각도 들어서 리뷰어님께 조언을 구하고싶습니다.

2023-05-08 15:39 UTC, galcyurio requested changes
마지막 단계까지 고생하셨습니다.
질문해주신 부분들을 위주로 피드백을 남겨두었습니다.
확인 후 다시 요청해주세요!

2023-05-08 15:39 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/model/data/local/BookedTicketPreference.kt
> +@kotlinx.serialization.Serializable
이런 경우에는 import alias 또는 typealias를 활용해보세요.
하나의 파일에서만 다른 이름을 쓰고 싶으면 import alias, 여러 파일에서 공통적으로 쓰도록 만들고 싶다면 typealias를 사용할 수 있습니다.

```kotlin
import kotlinx.serialization.Serializable as KtSerializable

@KtSerializable
```

```kotlin
typealias KtSerializable = kotlinx.serialization.Serializable

@KtSerializable
```

2023-05-08 15:39 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/model/data/local/BookedTicketPreference.kt
> +class BookedTicketPreference(private val context: Context) : BookedTicketStorage {
현재 구조는 SharedPreference에 저장할 DTO 타입만큼 계속해서 이런 클래스를 선언해야 합니다.
어떻게 하면 하나의 클래스에서 고정된 함수들을 가지고 재사용할 수 있도록 만들 수 있을까요?

<details>
<summary><h2>힌트<h2></summary>
<br>

특정 DTO를 저장하는 함수 대신에 Int, Long과 같은 원시타입을 key value로 저장하는 함수를 선언해보세요.
만들다보면 SharedPreference가 이미 그런 역할이라 필요없다고 생각하실수도 있습니다.

</details>

2023-05-08 15:39 UTC, galcyurio commented on app/src/test/java/woowacourse/movie/presentation/booking/BookingPresenterTest.kt
> +class BookingPresenterTest {
> MVP 형태로 도메인을 액티비티로 부터 뜯어내고 Presenter를 테스트하기 좋은 형태로 만들려고 노력해봤습니다.
또한 Presneter test에 집중해 보았는데 맞는 형태로 했는지 잘모르겠습니다ㅠㅠ.

대부분의 Presenter 테스트 코드 잘 작성해주셨습니다.
테스트 코드를 작성하시면서 MVP에 대한 장단점을 많이 느끼셨을텐데 그 부분을 계속해서 기억해두시고 추후에 어떻게 개선할 수 있을지 고민해보시면 좋겠습니다.

2023-05-08 15:39 UTC, galcyurio commented on app/src/test/java/woowacourse/movie/presentation/booking/BookingPresenterTest.kt
> +class BookingPresenterTest {
추가로 프로덕션 코드에서는 에러가 나지 않지만 테스트 코드에서는 컴파일이 실패하고 있습니다.

2023-05-08 15:39 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/presentation/booking/BookingActivity.kt
> +        initPresenter()
적절한 생명주기에 Presenter 초기화 :+1:

2023-05-08 15:39 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/model/data/local/BookedTicketPreference.kt
> +class BookedTicketPreference(private val context: Context) : BookedTicketStorage {
> 그리고 지난번에 조언해주신대로 미리 서버와 통신한다는 가정하에 추상화를 한번거쳐서 더미데이터들을 배치해서 나중에 변경에 쉽게 대응할수있게 했습니다. ( 레포지토리와 데이터소스라고 네이밍하고 사용하면, 제대로 알고 쓰라고 혼날것 같아서 추상화를 한단계만 거쳐서 비슷한 역할을 할수있도록 해보았습니다.)

추후에 clean architecture에 대해서 공부해보고 의존성 역전 원칙이 무엇인지 왜 써야 하는지를 알게 되신 후에 Repository 패턴을 구현해보세요.

2023-05-08 15:39 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/model/data/local/TicketIssuePreference.kt
> +    }
> 1.Ticket객체에 Id 값 부여
이것이 정상적인 앱이라면 서버와 통신해서 서버에서 Ticket을 발급하고 거기서 auto Increment 같은 것들로 Id 값을 중복되지않도록 관리해야 한다고 생각합니다. 하지만 현재는 서버가 없기 때문에 Ticket의 고유 값을 갖기위해 코틀린 자체에서 인스턴스를 생성할때마다 auto Increment 같이 ID 값을 부여할수 있는 방법을 찾아보았으니 찾지 못하였습니다.
그래서 local저장소(sharedPreference사용)에 인스턴스를 생성할때마다 1씩 늘려서 Id값을 부여하도록 했습니다.
이에 따라 TicketModle을 사용하는 모든 곳에서 context를 받아야했기 때문에 안드로이드 의존성이 강하게 발생하였습니다.
이럴때 코틀린 자체에서 Id값을 부여하거나 안드로이드와 관련없이 순수 자바 코틀린 모듈에서도 저장소를 관리 유지할수있는 방법이 있을까요?
(물론 안드로이드가 저장공간을 갖고있는건데 안드로이드없이 저장공간을 확보한다는게 말이 안된다고 생각합니다.)

2가지 방법이 있습니다.

로컬 DB인 SQLite의 auto increment를 활용하면 ID를 자동으로 1씩 늘릴 수 있습니다.

만약 로컬 DB를 쓰지 않고 ID를 생성하려면 순수 자바에서도 사용할 수 있는 UUID를 사용하시면 됩니다. (UUID.randomUUID().toString())
UUID는 충돌이 발생하지 않도록 고안된 식별자입니다. 
이론상으로는 충돌할 수 있지만 버전 4의 UUID는 1/2^62의 확률로 충돌할 수 있고 이는 전세계의 사람들이 동시에 각각 1조개의 주사위를 던졌을 때, 같은 숫자가 나올 정도의 천문학적인 확률이므로 안심하고 사용하셔도 됩니다.

2023-05-08 15:39 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/model/data/local/BookedTicketPreference.kt
> +    @kotlinx.serialization.Serializable(with = LocalDateTimeComponentSerializer::class)
> 이번 미션에서 저장소에 많은 힘을 쓰고싶지않아서 예매 영화내역을 sharedPreference 에다가 저장하려고 시도했고 객체의 리스트를 집어넣기위해 Json으로 파싱해서 집어넣고 그것을 다시 직렬화 해서 사용하려 시도하였습니다.
그러면서 많은 뻘짓을 했고 왜 간단한 데이터 저장만 sharedPreference를 사용하고 복잡한것들은 다른것을 사용하는지 꺠달았습니다.
근데 이때 직렬화를 위해서 기존에 주로 사용하던 Gson 이 아닌 kotlinx serialization 을 사용하게 되었습니다.
kotlinx serialization을 사용하게 된 이유는 코틀린에 맞춰서 몇가지 기능들이 더 제공된다고 해서 사용해봤는데
localDateTime도 제대로 처리못하는것을 보고 충격과 공포와함께 그냥 Gson 쓸걸 이라는 생각을 50000 번 했습니다.
이럴때 항상 드는 고민이 라이브러리의 선택기준이 참애매하고 생각합니다.


직렬화, 역직렬화 라이브러리는 크게 Reflection 방식과 code-generation 방식 2개가 있습니다.
gson의 경우에는 reflection 방식이고 `kotlinx.serialization`은 code-genration 방식입니다.

reflection 방식은 편하지만 code generation 방식이 성능적으로는 훨씬 뛰어나고 안전합니다.
자세한 이유에 대해서는 아래 글을 참고해보세요.
https://velog.io/@suev72/Gson%EC%97%90%EC%84%9C-kotlinx-serialization%EB%A1%9C-%EA%B0%88%EC%95%84%ED%83%84-%EC%9D%B4%EC%9C%A0

위 글 말고도 gson의 단점이 많은데 조금 더 자세히 알고 싶다면 moshi와 gson을 비교한 글을 읽어보셔도 좋습니다.
https://proandroiddev.com/goodbye-gson-hello-moshi-4e591116231e

> 최근에 나온 새로운 기능을 탑재한 라이브러리랑 검증된 라이브러리중 리뷰어님은 어떤기준에 따라 어떤걸 사용하시는지 궁금합니다.

검증된 라이브러리를 사용하고 최근에 나온 것은 정말 필수적인 기능이 아닌 이상 실무에서는 잘 사용하지 않는 편입니다.
그 이유는 검증된 라이브러리를 사용하면 어떠한 문제가 발생하더라도 해당 문제를 이미 겪은 사람들이 있고 이에 대한 해결책도 여러가지가 나와있기 때문이에요.

2023-05-08 15:39 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/model/data/local/BookedTicketPreference.kt
> +    @kotlinx.serialization.Serializable(with = LocalDateTimeComponentSerializer::class)
참고로 Gson도 Date는 처리해주지만 LocalDateTime은 별도로 TypeAdapter를 만들어야 합니다.

개인적으로는 Moshi를 사용해서 딱히 kotlinx.serialization에 대한 필요성을 느끼지 못했고 사용해보지도 않았습니다.
Moshi는 reflection 방식과 code-generation 방식을 모두 지원하고 kotlin으로 만들어졌기 때문에 kotlin에 대한 지원도  좋습니다.

2023-05-08 15:39 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/presentation/booking/BookingPresenter.kt
> +    private val movieTheaterStorage: MovieTheaterStorage
> presenter를 만들다보니 생성자를 통해서 주입받아야할게 너무많고 (Dependency Injection을 통해 테스트 가능성을 열기위해)
그러다보니 presneter가 갖고있는 프로퍼티가 진짜 너무 많아졌습니다. level1 을 진행하며 프로퍼티가 너무많은것은 안좋다고 배웠기에
줄여야하나 생각해보았지만 사실 이것은 어쩔수없는것 아닌가? 라는생각도 들어서 리뷰어님께 조언을 구하고싶습니다.

저도 이 부분은 정석적으로는 각 역할별로 View를 나누어서 그 만큼 Presenter도 가볍게 해야 한다고 생각은 합니다.

하지만 실무에서 직접 유지보수를 하다보면 생성자가 10~20개의 매개변수를 받는 경우도 생기는데 그런 상황에서 '분리하는게 정말 맞는가?'를 생각해보면 '여기서 어떻게 나누지?'라는 생각이 들고 이미 역할별로 잘 나누어졌다고 생각되어서 그대로 두는 경우가 많습니다 😅
이 부분은 저도 명확히 답변을 드리기가 힘드네요. 🙏

2023-05-14 07:38 UTC, 2chang5 commented on app/src/main/java/woowacourse/movie/model/data/local/BookedTicketPreference.kt
> +@kotlinx.serialization.Serializable
import alias 너무 좋은것 같습니다 적용해봤습니다

2023-05-28 01:13 UTC, 2chang5 commented on app/src/main/java/woowacourse/movie/model/data/local/TicketIssuePreference.kt
> +    }
UUID를 사용하면 되는것이였군요 chapgpt에서 추천해줬지만 불신했었는데 ㅎㅎㅎㅎ. 앞으로 사용할일이 생긴다면 활용해보겠습니다

2023-05-28 05:50 UTC, 2chang5 commented on app/src/test/java/woowacourse/movie/presentation/booking/BookingPresenterTest.kt
> +class BookingPresenterTest {
테스트코드도 컴파일이 정상적으로 작동하도록 수정하였고 기존 sharedPrefertence를 clear하고 다시 설정하여 저장소에 영향이 가는 테스트를 Mockk 을 사용하여 실제 저장소에 영향을 가지 않도록 테스트를 변경해보았습니다.
이부분에 대해서 테스트가 익숙하지않아 혹시 비효율적으로 코드를 짠것아닌가 궁금합니다. 조언부탁드립니다

2023-05-28 06:40 UTC, 2chang5 commented on app/src/main/java/woowacourse/movie/model/data/local/BookedTicketPreference.kt
> +class BookedTicketPreference(private val context: Context) : BookedTicketStorage {
> 추후에 clean architecture에 대해서 공부해보고 의존성 역전 원칙이 무엇인지 왜 써야 하는지를 알게 되신 후에 Repository 패턴을 구현해보세요.

이 부분에대해서 학습한 내용으로 clean architecture의 주요 내용은 의존성이 과녁그림처럼 항상 
Presentation layer,Data layer가 Domain Layer를 항해 의존성을 가지도록 설계해야하는것으로 
난잡하게 Presentation Layer 가 Data Layer에 의존성을 갖는등의 행위를 금지하고 의존성이 한방향으로 흘러야하는 것으로 공부하였습니다.

이런 의존관계를 만족시키기 위해 Repository패턴을 구현할 때 interface는 domain layer에 위치시키고 구현은 Data layer에서 함으로써 데이터를 가져다 쓰는 Presentation layer에서는 Domain Layer에 대해서만 의존성을 갖도록 설계하는것이라고 이해하였는데 혹시 맞을까요?

2023-05-28 09:52 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/model/data/local/BookedTicketPreference.kt
> +class BookedTicketPreference(private val context: Context) : BookedTicketStorage {
> 이 부분에대해서 학습한 내용으로 clean architecture의 주요 내용은 의존성이 과녁그림처럼 항상
Presentation layer,Data layer가 Domain Layer를 항해 의존성을 가지도록 설계해야하는것으로
난잡하게 Presentation Layer 가 Data Layer에 의존성을 갖는등의 행위를 금지하고 의존성이 한방향으로 흘러야하는 것으로 공부하였습니다.


네, 의존성이 한 방향으로만 흘러야 합니다.
다만 presentation layer에서 data layer에 의존하더라도 의존성 규칙에 어긋나지 않습니다. (presentation -> data -> domain)

> 이런 의존관계를 만족시키기 위해 Repository패턴을 구현할 때 interface는 domain layer에 위치시키고 구현은 Data layer에서 함으로써 데이터를 가져다 쓰는 Presentation layer에서는 Domain Layer에 대해서만 의존성을 갖도록 설계하는것이라고 이해하였는데 혹시 맞을까요?

의존관계를 만족시키기 위함이 아니라 domain layer에서 데이터를 가져오고 저장해야 하는 경우가 생깁니다.
문제는 이러한 로직들이 domain layer에 위치하면 SQLite와 같이 안드로이드에 의존적인 코드가 포함되어야 해서 플랫폼에 종속되어버립니다.
그래서 상위 layer(domain)에서 하위 layer(data)의 기능을 활용할 때는 [의존성 역전](https://velog.io/@harinnnnn/OOP-%EA%B0%9D%EC%B2%B4%EC%A7%80%ED%96%A5-5%EB%8C%80-%EC%9B%90%EC%B9%99SOLID-%EC%9D%98%EC%A1%B4%EC%84%B1-%EC%97%AD%EC%A0%84-%EC%9B%90%EC%B9%99-DIP)이라는 방식을 활용합니다.
이 의존성 역전 원칙을 코드로 구현하면 interface는 domain layer에 위치하고 구현체는 data layer에서 위치하게 됩니다.

의존성 역전은 아키텍쳐를 설계하면서 굉장히 유용하고 많이 쓰이는 개념이니 이번 기회에 공부해보세요!

2023-05-28 09:53 UTC, galcyurio commented on app/src/test/java/woowacourse/movie/presentation/booking/BookingPresenterTest.kt
> +class BookingPresenterTest {
commit을 push 해주시면 확인해보겠습니다!

2023-05-28 09:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/movie/model/data/local/BookedTicketPreference.kt
> +class BookedTicketPreference(private val context: Context) : BookedTicketStorage {
아아 여태껏 잘못 이해하고있었습니다!! 정정해주셔서 감사합니다!!! 의존성 역전법칙에 대해선 추가 학습해보도록 하겠습니다!!!

2023-05-28 09:59 UTC, 2chang5 commented on app/src/main/java/woowacourse/movie/model/data/local/BookedTicketPreference.kt
> +    @kotlinx.serialization.Serializable(with = LocalDateTimeComponentSerializer::class)
좋은 블로그 글 감사드립니다!!! moshi가 많은 기능을 제공하는지 몰랐네요 ㅎㅎㅎ 나중에 시간이 나는대로 라이브러리에 대해서 정리해보겠습니다!!

2023-05-28 11:13 UTC, galcyurio approved these changes
마지막까지 피드백 반영하느라 고생하셨습니다 👍 
한 가지 코멘트를 남겨두었으니 확인해주세요!
다른 미션에 집중하실 수 있도록 이번 미션은 여기서 마무리하도록 하겠습니다.

2023-05-28 11:13 UTC, galcyurio commented on app/src/androidTest/java/woowacourse/movie/presentation/settings/SettingsFragmentTest.kt
>      }
> 테스트코드도 컴파일이 정상적으로 작동하도록 수정하였고 기존 sharedPrefertence를 clear하고 다시 설정하여 저장소에 영향이 가는 테스트를 Mockk 을 사용하여 실제 저장소에 영향을 가지 않도록 테스트를 변경해보았습니다.
이부분에 대해서 테스트가 익숙하지않아 혹시 비효율적으로 코드를 짠것아닌가 궁금합니다. 조언부탁드립니다

테스트는 가능한 한 실제 객체로 테스트해보는것이 좋습니다.
최대한 배포되었을 때의 환경과 비슷하게 맞춰서 테스트해야 실제로 발생할 수 있는 에러들을 잡아낼 수 있기 때문이에요.
그래서 이전 코드처럼 실제 SharedPreference를 사용하고 시작할 때 clear 하거나 미리 다른 데이터를 넣어두는게 오히려 실제 환경과 비슷합니다.

2023-05-28 11:13 UTC, merged