[영화 극장 선택] 하디 1, 2단계 미션 제출합니다.
woowacourse/android-movie-theater pull request #62
Opened 2024-05-02 07:55 UTC by murjune

2024-05-03 02:32 UTC, malibinYun requested changes
1, 2단계 미션 고생 많으셨어요!
여러 생각해볼 만한 곳에 코멘트 남겨두었으니, 충분히 고민해보는 시간 가져보세요!
피드백 반영 후 다시 리뷰 요청 부탁드려요 :)

2024-05-03 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/HomeActivity.kt
> +        }
fc_main은 무슨 뜻인가요?
축약어는 최대한 지양해보는 건 어떨까요?

2024-05-03 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/HomeActivity.kt
> +            else -> error("Invalid itemId: $itemId")
보여지는 프래그먼트가 바뀔 때마다 새로운 프래그먼트를 생성하지 않겠네요 👍

2024-05-03 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/movieDetail/MovieDetailActivity.kt
> +
times만 따로 멤버로 둔 특별한 이유가 있었나요?

2024-05-03 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/movieDetail/MovieDetailActivity.kt
> +        presenter.generateDateRange()
setupEventListeners(cinama) 이것과 비교했을 때 어떤 점이 let을 쓰는 것이 더 나았나요?

2024-05-03 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/movieDetail/MovieDetailActivity.kt
> +        binding.movieDateSpinner.onItemSelectedListener =
값을 업데이트 할 때마다 어뎁터를 새로 만들어 세팅해 주어야할까요?

2024-05-03 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/movieDetail/MovieDetailActivity.kt
> +                        "timeDate",
String Key에 변경이 조금이라도 생겼을 때, 이 값을 받아야하는 화면들에 모두 안전하게 변경해낼 수 있을까요?

2024-05-03 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/movieDetail/MovieDetailActivity.kt
> +                    )
지금은 컴파일러가 똑똑해서 + 를 사용했을 때 문제가 발생하지 않을 수 있지만,
String 을 + 로 더해가는 건 어떤 문제를 일으킬 수 있을까요?
buildString 함수를 활용해보는 건 어떨까요?

2024-05-03 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/movieList/MovieListFragment.kt
> +    private val presenter get() = _presenter ?: error(getString(R.string.null_point_error))
이렇게 필드를 구성하면 어떤 점에 장단점이 있었나요?
다른 방법들도 고민해보고, 그 방법들은 어떤 장단점이 있을지 고민해보시면 좋겠어요 :)

2024-05-03 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/movieList/MovieListFragment.kt
> +        binding.rvMovies.layoutManager = LinearLayoutManager(requireContext())
LayoutManager는 xml에서 세팅해보는 건 어떨까요?

2024-05-04 15:49 UTC, murjune commented on app/src/main/java/woowacourse/movie/HomeActivity.kt
> +        }
fragment_container_home 으로 수정하겠습니다!

2024-05-04 15:54 UTC, murjune commented on app/src/main/java/woowacourse/movie/movieDetail/MovieDetailActivity.kt
> +
없습니다..! presenter 로 옮기겠습니다 💪

2024-05-04 15:55 UTC, murjune commented on app/src/main/java/woowacourse/movie/movieDetail/MovieDetailActivity.kt
> +        presenter.generateDateRange()
불필요한 스코프 함수인 것 같습니다..! 수정하겠습니다 💪

2024-05-04 15:56 UTC, murjune commented on app/src/main/java/woowacourse/movie/movieDetail/MovieDetailActivity.kt
> +                        "timeDate",
하드코딩된 키 값을 상수화해두겠습니다..!

2024-05-04 16:03 UTC, murjune commented on app/src/main/java/woowacourse/movie/movieDetail/MovieDetailActivity.kt
> +                    )
매 String 연산마다 새로운 String 객체가 만들어져 메모리적으로 비 효율적인 것 같습니다!  
수정하겠습니다..! 💪

2024-05-04 16:04 UTC, murjune commented on app/src/main/java/woowacourse/movie/movieList/MovieListFragment.kt
> +        binding.rvMovies.layoutManager = LinearLayoutManager(requireContext())
수정하겠습니다..!

2024-05-04 16:07 UTC, murjune commented on app/src/main/java/woowacourse/movie/movieList/MovieListFragment.kt
> +    private val presenter get() = _presenter ?: error(getString(R.string.null_point_error))
presenter 의 경우 백킹 프로퍼티가 불필요한 것 같아 lateinit 으로 바꾸었습니다..!  

---  

binding 의 경우에는 Fragment와 Fragment View의 생명주기가 다르기 때문에 Memory Leak이 발생할 수 있습니다.(e. replace + addToBackStack)

따라서, 위와 같이 수동으로 메모리를 할당해주어야 하는데요!  
매번 불필요한 null 검사를 하지 않기 위해 백킹 프로퍼티를 사용했습니다!

2024-05-04 16:26 UTC, murjune commented on app/src/main/java/woowacourse/movie/movieDetail/MovieDetailActivity.kt
> +        binding.movieDateSpinner.onItemSelectedListener =
매번 어뎁터를 생성해주는건 너무 비효율적인 것 같습니다!
내부 items 만 갈아 끼우도록 리팩토링하겠습니다. 💪

2024-05-05 08:30 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/movieList/MovieListFragment.kt
> +    private val presenter get() = _presenter ?: error(getString(R.string.null_point_error))
매번 수행하는 null 검사가 정말 불필요할까요?
오히려 null인 경우 런타임에서 반드시 IllegalStateException이 발생하게 되어, 앱이 비정상 종료되는 경우가 더 발생할 것으로 보이네요.
사용자로 하여금 비정상 종료되는 앱은 좋은 사용성을 제공해줄 수 있을까요?

2024-05-05 09:19 UTC, murjune commented on app/src/main/java/woowacourse/movie/movieList/MovieListFragment.kt
> +    private val presenter get() = _presenter ?: error(getString(R.string.null_point_error))
앗.. 제가 답변을 잘못한 거 같습니다 😅    

> 사용자로 하여금 비정상 종료되는 앱은 좋은 사용성을 제공해줄 수 있을까요?  

만약 제가 사용하는 앱에 비정상 종료가 빈번하게 발생할 경우, 사용하고 싶지 않을 것 같습니다..  

> 오히려 null인 경우 런타임에서 반드시 IllegalStateException이 발생하게 되어, 앱이 비정상 종료되는 경우가 더 발생할 것으로 보이네요.

binding 의 경우, onCreateView ----> onDestroyView(ViewLifeCyle) 에서만 사용 가능한 프로퍼티입니다.  
binding이 ViewLifeCycle을 따라가도록 한다면, ViewLifecycle 내에서는 null이 안들어갈 것이라 판단하여
위와 같은 로직을 작성하였습니다!

```kotlin
    private var _binding: FragmentMovieListBinding? = null
    private val binding get() = _binding ?: error(getString(R.string.null_point_error)) 
// onCreateView ~ onDestroyView 에서만 사용가능!
```

그러나, Binding과 Fragment에 2가지 생명주기를 잘 인식하지 못한 개발자가  
onCreate 에 binding 프로퍼티를 작성할 경우, 비정상 종료가 발생하겠네요.. 

혹시 좋은 방법이 있다면 말씀해주시면 감사하겠습니다 🙇‍♂️

2024-05-05 09:21 UTC, murjune commented
안녕하세요 말리빈!  
피드백 주신 부분 반영했습니다 💪

2024-05-06 09:22 UTC, malibinYun approved these changes
1, 2단계 미션 고생 많으셨어요.
다음 미션 진행을 위해 머지할게요!
피드백은 다음 미션에서 반영해주세요 :)

2024-05-06 09:22 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/model/movieInfo/MovieDate.kt
> +    override fun toString(): String = "${date.year}.${date.monthValue}.${date.dayOfMonth}"
다른 View에서는 시간을 다르게 표기해야한다면, 이 코드는 어떻게 변하게 될까요?

2024-05-06 09:22 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/movieDetail/MovieDetailActivity.kt
> +        binding.movieTimeSpinner.adapter = timeAdapter
스피너에 대한 일을 객체로 분리해보는 건 어떨까요?

2024-05-06 09:22 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/movieDetail/MovieDetailContract.kt
> +        fun navigateToPurchaseConfirmation(intent: Intent)
이 메서드는 Presenter에서 View로 명령을 보낼 때 쓰이지 않고있네요.
인터페이스로써 존재하는 의미가 있을지 고민해보세요 :)

2024-05-06 09:22 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/movieList/cinemaListDialog/CinemaAdapter.kt
> +    ListAdapter<Cinema, TheaterViewHolder>(theaterComparator) {
ListAdapter를 쓰기 이전, 먼저 RecyclerView.Adapter를 먼저 구현해보는 건 어떨까요?

2024-05-06 09:22 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/movieList/cinemaListDialog/TheatersBottomSheetFragment.kt
> +    }
꼭 `this::class.java.canonicalName`여기에 접근해서 nullable String으로 TAG 변수를 채워야할까요?
Tag를 원하는 문자열로 입력하는 것과는 어떤 장단점이 있었나요

2024-05-06 09:22 UTC, malibinYun commented on app/src/main/res/layout/activity_movie_detail.xml
> +                    android:text="@{presenter.movie.title.toString()}"
MVP아키텍처가 수행하는 일들에 대해 다시 한 번 학습해보세요.
Presenter내부의 값을 참조하는 것은 MVP 아키텍처에서 허용하는 일일까요?

2024-05-06 09:22 UTC, malibinYun commented on app/src/test/java/woowacourse/movie/SeatPresenterTest.kt
> +    }
애너테이션을 활용했다면, 필요한 실제 객체를 만드는 것도 애너테이션을 활용할 수 있어요 :)
어떤 기능일지 찾아보고 개선해보세요!

2024-05-06 09:22 UTC, malibinYun commented on app/src/test/java/woowacourse/movie/SeatPresenterTest.kt
> +        colorSlot.captured shouldBe expectedColor
이 테스트에서는 capture slot의 활용이 불필요해 보이네요.
어떻게 개선해볼 수 있을까요?

2024-05-06 09:22 UTC, malibinYun commented on app/src/test/java/woowacourse/movie/SeatPresenterTest.kt
> +        seatTwoColorSlot.captured shouldBe redColor
assertAll로 감싸는 것과 아닌 것의 차이는 무엇일까요?

2024-05-06 09:22 UTC, merged

2024-05-06 09:25 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/movieList/MovieListFragment.kt
> +    private val presenter get() = _presenter ?: error(getString(R.string.null_point_error))
전략은 매우 많이 생겨날 수 있겠지요!
다만 이 방법은 직접 `binidng?.~~` 이렇게 다루는 것에 비해 안정성 차이에서 매우 많이 난다는 생각이 드네요 :)

2024-05-07 10:02 UTC, murjune commented on app/src/main/java/woowacourse/movie/model/movieInfo/MovieDate.kt
> +    override fun toString(): String = "${date.year}.${date.monthValue}.${date.dayOfMonth}"
UiModel 과 string res 를 활용해 개선해보겠습니다 💪

2024-05-11 15:57 UTC, murjune commented on app/src/main/java/woowacourse/movie/movieDetail/MovieDetailContract.kt
> +        fun navigateToPurchaseConfirmation(intent: Intent)
Presenter가 View로 명령을 보내는 능동적인 객체로 리팩토링 해보겠습니다!

2024-05-11 15:57 UTC, murjune commented on app/src/main/java/woowacourse/movie/movieList/cinemaListDialog/CinemaAdapter.kt
> +    ListAdapter<Cinema, TheaterViewHolder>(theaterComparator) {
MovieAdapter, ReservationAdapter 에서는 RecyclerView.Adapter를 구현했습니다!
CinemasAdapter 에서는 ListAdapter를 사용해보고 싶었습니다..!

2024-05-11 15:58 UTC, murjune commented on app/src/main/java/woowacourse/movie/movieList/cinemaListDialog/TheatersBottomSheetFragment.kt
> +    }
> 꼭 this::class.java.canonicalName여기에 접근해서 nullable String으로 TAG 변수를 채워야할까요?  

simpleName 으로 수정하였습니다..!   
canonicalName 을 사용했던 이유는 패키지 경로도 함께 포함되어  
고유한 키값으로 사용하고 싶었습니다!  

> Tag를 원하는 문자열로 입력하는 것과는 어떤 장단점이 있었나요  

 문자열을 수동으로 입력하는 것은 개발자의 실수를 야기할 가능성이 있다고 생각합니다.  
따라서, 해당 파일 만의 고유한 tag 값을 사용하는것 을 지향합니다.  

다만, `simpleName` 으로 리팩토링할 경우 동일한 이름의 class 가 존재할 수 있으니 tag 중복이 발생할 수 있을 것 같네요.. 🥲

2024-05-11 15:58 UTC, murjune commented on app/src/main/res/layout/activity_movie_detail.xml
> +                    android:text="@{presenter.movie.title.toString()}"
Presenter 가 값을 반환하도록 하는 것은 MVP 구조가 아닌 것 같습니다.  수정하겠습니다 💪

2024-05-11 15:58 UTC, murjune commented on app/src/test/java/woowacourse/movie/SeatPresenterTest.kt
> +    }
`InjectMockKs` 애너테이션을 활용해서 개선했습니다 💪

2024-05-11 15:58 UTC, murjune commented on app/src/test/java/woowacourse/movie/SeatPresenterTest.kt
> +        colorSlot.captured shouldBe expectedColor
해당 테스트는 slot 을 사용하지 않고, 예상값으로도 충분히 test 가능한 것 같습니다!
---  

테스트에서 capture slot을 사용할 경우, verify 문을 사용할 필요가 없을 것 같다는 생각이 듭니다.🤔 이미, 호출된 순서대로 값들을 모두 slot에 저장하고 있기 때문인데요
 말리빈은 어떻게 생각하시나요?!

2024-05-11 15:58 UTC, murjune commented on app/src/test/java/woowacourse/movie/SeatPresenterTest.kt
> +        seatTwoColorSlot.captured shouldBe redColor
assertAll 로 감쌀 경우, 중간에 테스트가 실패해도 그 뒤에 있는 테스트를 계속 검사할 수 있습니다. 수정하겠습니다 🚀