[영화 극장 선택] 꼬상 1, 2단계 미션 제출합니다.
woowacourse/android-movie-theater pull request #67
Opened 2024-05-02 08:15 UTC by kkosang

파이로 안녕하세요 :) 
영화 극장 선택 미션을 리뷰 받게된 꼬상이라고 합니다 !

안드로이드 개발을 처음 해봐서 기능 구현에 미흡하지만 코드리뷰 잘 부탁드립니다 🙇🏻‍♂️

--- 
페어와 함께 작업한 내용입니다 
https://github.com/kkosang/android-movie-theater/compare/d8638cf60b737bc23f5f904b7cbb25fd839d52ea..e420352348362110056382f945cb74f44e051da0

2024-05-02 21:33 UTC, ghojeong requested changes
<img width="533" alt="스크린샷 2024-05-03 오전 6 31 56" src="https://github.com/woowacourse/android-movie-theater/assets/38595650/33e798ca-e39d-4e38-945f-3e980b28bc73">

안녕하세요 꼬샹!
미션을 함께하게된 파이로 입니다.
린트를 통과하지 못하고 있는 것 같은데 확인 바랍니다.

2024-05-02 23:04 UTC, kkosang commented
안녕하세요 파이로 !
좋은 아침입니다 !!
 
꼼꼼하게 확인하지 못한 것 같네요...😅
린트체크 후 다시 리뷰 요청 드립니다 :) 

린트체크 적용된 커밋부분 까지 추가하였습니다 !
https://github.com/kkosang/android-movie-theater/compare/e420352348362110056382f945cb74f44e051da0..ca69cdb8e81cafe99ac84a0fe08200130984dd6f

2024-05-03 08:12 UTC, ghojeong requested changes
> 기능 구현이 우선이라고 생각해서 기능 구현을 하다보니 테스트 코드를 작성하지 못했습니다 🥲
> 스피너에 해당 데이터를 연결짓지 못했습니다.. ! 추후에 해당 기능을 추가하겠습니다

마감일을 지킬 수 있도록 신경써주신 점 감사합니다.
또한 리뷰어를 배려하여, 구현하지 못한 기능과 테스트 코드가 부족한 이유에 대해 설명 남겨주셔서 감사합니다. 🙇 
주말동안 시간 여유가 있으니 기능구현과 테스트 코드를 마저 완성 부탁드립니다.

본격적인 코드 리뷰를 하지 않은 이유는,
혹여 제 리뷰 때문에 꼬상이 기능 구현에 집중하지 못할까봐 입니다.
꼬상 만의 속도로 진행해도 괜찮으니, 기능 구현을 마무리하고,
그에 따른 테스트 코드 또한 전부 작성 부탁드립니다.

<video src="https://github.com/woowacourse/android-movie-theater/assets/38595650/a99578b3-ace2-42a6-89f3-603be67ffd34" />

2024-05-03 08:12 UTC, ghojeong commented on app/src/main/res/layout/theater_item.xml
> +        <TextView
![problem](https://github.com/woowacourse/android-movie-theater/assets/38595650/c9c0f98d-06cf-46b3-8dfe-57e15f764009)

ui가 겹치는 문제가 있네요 😭

2024-05-03 08:12 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/view/navigation/Home.kt
> +class Home : Fragment(), ScreeningContract.View, ScreeningContract.ViewActions {
보통 네이밍을 ~Fragment 로 씁니다 `HomeFragment`

2024-05-05 09:26 UTC, kkosang commented on app/src/main/res/layout/theater_item.xml
> +        <TextView
> ui가 겹치는 문제가 있네요 😭

이 부분도 결과 페이지와 마찬가지로, 크기를 지정해두고 그 크기를 넘어가면 ..으로 출력되도록 수정하였습니다 !

2024-05-05 14:24 UTC, kkosang commented
안녕하세요 파이로 !

안드로이드 개발도 처음인 상태에서, 페어의 코드로 작업 하느라 생각보다 오래 걸렸네요 😂
위에 남겨주신 리뷰와 기존에 스피너를 연결 짓지 못한 부분 적용하였습니다 !

--- 
https://github.com/kkosang/android-movie-theater/compare/e420352348362110056382f945cb74f44e051da0..2d756e03771d70ee8ee4567a3bbc975f03ceaf4d

2024-05-06 04:30 UTC, ghojeong requested changes
꼬샹!
기능구현 해주시며 단위 테스트 무척 훌륭하게 작성해주셨습니다! 👍 💯 
Presenter 에 관한 테스트도 보완하면 좋을 것 같아서 요청드립니다!
테스트 마저 보완해주시면 본격적으로 깊게 리뷰하겠습니다!

2024-05-06 04:30 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/view/reservation/seat/SeatSelectionPresenterImpl.kt
> +    ) {
TODO 가 남아있어서 여쭈어봅니다.

2024-05-06 04:30 UTC, ghojeong commented on app/src/test/java/woowacourse/movie/model/reservation/date/ScreeningDateTimeTest.kt
> +        )
레벨 2에서 미션을 진행하다보면, 
레벨 1에서 배웠던 단위 테스트를 소홀히 하게 되는 경우가 많은데,
꼼꼼히 단위 테스트를 작성해주신 점 무척 멋집니다. 👍 💯 

다음 단계 미션 진행을 하시거나 리팩토링을 하실 때에도,
단위 테스트 욕심을 께속 내주시면 감사하겠습니다.

2024-05-06 04:30 UTC, ghojeong commented on app/src/test/java/woowacourse/movie/presentation/view/screening/theater/TheaterBottomSheetPresenterImplTest.kt
> +        verify(exactly = 1) { view.showTheaterInfo(theatersInfo) }
Presenter 에 대한 테스트를 할 때 given-when-then 형식으로 해주신 점 또한 멋집니다. 👍 💯

2024-05-06 04:30 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/view/reservation/detail/MovieDetailPresenterImpl.kt
> +    }
도메인 테스트에 비해 Presenter 에 대한 테스트는 아직 빈약한 것 같습니다.
모처럼 레벨 2에 오셨으니 Presenter 에 대한 테스트도 보완 부탁드립니다!

다만 도메인 테스트를 훌륭하게 작성해주신 것을 다시 칭찬드립니다. 👍 💯 

앞으로도 시간이 부족해서 우선순위를 정해야한다면,
기능구현이 최우선, 단위 테스트가 그 다음,
그 다음 여유가 생기면 MockK 를 활용한 테스트에 도전해주세요!

2024-05-06 12:21 UTC, ghojeong requested changes
꼬상!
저희 미션 프로그래밍 요구 사항 중에서
**DataBindin 을 사용해야 한다.**
가 있는데 사용을 하지 않고 있는 부분이 있어서 
findViewById 를 전부 dataBinding 으로 바꿔달라고 요청드립니다.

2024-05-06 12:21 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/uimodel/MovieTicketUiModel.kt
> +) : Parcelable {
https://developer.android.com/kotlin/parcelize?hl=ko
`@Parcelable` annotation 한 번 확인해보시길 추천드립니다:)

2024-05-06 12:21 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/uimodel/MovieTicketUiModel.kt
> +    fun totalPrice(): String = "${String.format("%,d", totalPrice)}원 (현장 결제)"
원 (현장 결제) 도 String resource 로 관리하는게 어떨까요?

2024-05-06 12:21 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/view/navigation/HomeFragment.kt
> +        movieListView.layoutManager = LinearLayoutManager(context)
```app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"``` 이렇게 xml 로 설정하는 방법도 있습니다:)

2024-05-06 12:21 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/view/navigation/HomeFragment.kt
> +        val movieListView = view.findViewById<RecyclerView>(R.id.movieList)
findViewById 는 전부 dataBinding 을 활용해서 바꿔주시길 바랍니다.
<img width="255" alt="image" src="https://github.com/ghojeong/woowacourse-android/assets/37360089/145fed33-e98a-4898-bae7-e6bb8be3421d">

2024-05-06 12:52 UTC, kkosang commented on app/src/main/java/woowacourse/movie/presentation/view/reservation/detail/MovieDetailPresenterImpl.kt
> +    }
> 앞으로도 시간이 부족해서 우선순위를 정해야한다면, 기능구현이 최우선, 단위 테스트가 그 다음, 그 다음 여유가 생기면 MockK 를 활용한 테스트에 도전해주세요!

넵 명심하겠습니다 ! presenter에 대한 테스트도 보완하도록 하겠습니다 :)

2024-05-07 04:37 UTC, kkosang commented on app/src/main/java/woowacourse/movie/presentation/view/reservation/seat/SeatSelectionPresenterImpl.kt
> +    ) {
> TODO 가 남아있어서 여쭈어봅니다.

해당 부분은 작성해두고 지우는 것을 깜빡했습니다 😅

2024-05-07 05:37 UTC, kkosang commented on app/src/main/java/woowacourse/movie/presentation/uimodel/MovieTicketUiModel.kt
> +    fun totalPrice(): String = "${String.format("%,d", totalPrice)}원 (현장 결제)"
> 원 (현장 결제) 도 String resource 로 관리하는게 어떨까요?

context 객체가 없는 UiModel에서도 안드로이드 resource에 접근할 수 있나요 ?!

2024-05-07 05:43 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/uimodel/MovieTicketUiModel.kt
> +    fun totalPrice(): String = "${String.format("%,d", totalPrice)}원 (현장 결제)"
접근할 수 없다면, 생성자 혹은 함수 파라미터를 통해 주입받을 수 있도록 해주세요

2024-05-07 05:47 UTC, kkosang commented on app/src/main/java/woowacourse/movie/presentation/uimodel/MovieTicketUiModel.kt
> +) : Parcelable {
> https://developer.android.com/kotlin/parcelize?hl=ko `@Parcelable` annotation 한 번 확인해보시길 추천드립니다:)

참고자료 감사합니다 :)
수정하도록 하겠습니다 !

2024-05-07 05:55 UTC, kkosang commented on app/src/main/java/woowacourse/movie/presentation/view/navigation/HomeFragment.kt
> +        movieListView.layoutManager = LinearLayoutManager(context)
> `app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"` 이렇게 xml 로 설정하는 방법도 있습니다:)

감사합니다 :) 
기본적으로  `android:orientation="horizontal"` 설정되어 있군요 ! 
앞으로는 레이아웃 매니저 설정을 xml에 하도록 하겠습니다 !!

2024-05-07 06:13 UTC, kkosang commented on app/src/main/java/woowacourse/movie/presentation/uimodel/MovieTicketUiModel.kt
> +    fun totalPrice(): String = "${String.format("%,d", totalPrice)}원 (현장 결제)"
> 접근할 수 없다면, 생성자 혹은 함수 파라미터를 통해 주입받을 수 있도록 해주세요

context를 주입 받아서 String resource로 관리하니까 기존 코드보다 가독성도 좋고 재사용 하기에도 좋은 것 같네요 ! 👍 
감사합니다 :)

2024-05-07 06:53 UTC, kkosang commented
안녕하세요 파이로 !
원격에 push를 한번 하고, 커밋 실수를 발견해서 로컬에서 amend하고 마저 작업 후에 다시 push를 하는 바람에 충돌이 발생했었습니다..!
local의 작업을 원격으로 강제 푸시를 했습니다..
리뷰하실 때 참고 부탁드립니다 🙇🏻‍♂️

2024-05-07 07:18 UTC, ghojeong approved these changes
꼬상!
이번주도 해야할 작업이 많으리라 생각되어,
다음 단계 진행할 수 있도록 승인 후 머지하겠습니다.

수업을 듣고 나신 후 리팩토링해야 할게 많이 보이실 텐데, 
모두 적용해주시기 부탁드립니다.

2024-05-07 07:18 UTC, merged

2024-05-07 07:26 UTC, ghojeong commented
![force_push](https://github.com/woowacourse/android-movie-theater/assets/38595650/8db103eb-c05c-48c0-a0f2-24d0f3323ab1)

@kkosang 

참고로 협업 중에, 특히 PR 로 올린 원격 브랜치는 절대로 강제 푸시하면 안된다고 강제해봅니다.
저는 경력 초반에 코드 리뷰중인 내용을 강제 푸시하면 엄청 혼난 다음에 반성문도 써야 했습니다 .ㅋㅋㅋㅋ

2024-05-07 07:41 UTC, kkosang commented
> 참고로 협업 중에, 특히 PR 로 올린 원격 브랜치는 절대로 강제 푸시하면 안된다고 강조해봅니다. 저는 경력 초반에 코드 리뷰중인 내용을 강제 푸시하면 엄청 혼난(멱살이 잡혔습니다. ㅠㅠ) 다음에 반성문도 써야 했습니다 .

헉... 멱살.. 😥 
지금 경험해서 다행이라고 생각되네요..!
명심하고 또 명심하겠습니다 !! 🫡