[영화 극장 선택] 차람 1, 2단계 미션 제출합니다
woowacourse/android-movie-theater pull request #69
Opened 2024-05-02 08:24 UTC by aprilgom

안녕하세요! 안드로이드 6기 차람입니다!
영화 극장 선택 미션 리뷰 잘 부탁드립니다!

2024-05-02 23:49 UTC, KwonDae requested changes
차람 안녕하세요!
이번 극장 선택 미션 잘 부탁드립니다.

Presenter, Fragment, Adapter 위주로 코멘트를 남겨드렸으니
충분히 고민해보시고, 다시 요청 부탁드립니다!

2024-05-02 23:49 UTC, KwonDae commented on app/src/androidTest/java/woowacourse/movie/ScreeningMovieFragmentTest.kt
> +    }
제공해주는 데이터가 달라진다면 UiTest 코드도 변경되어야 하겠네요..!
어떤 데이터가 들어오든 테스트는 성공하게끔 하려면 어떻게 개선할 수 있을까요?

2024-05-02 23:49 UTC, KwonDae commented on app/src/androidTest/java/woowacourse/movie/ScreeningMovieFragmentTest.kt
> +            val listView = fragment.requireView().findViewById<RecyclerView>(R.id.rcv_screening_movie)
Fragment 테스트를 잘 작성해주셨네요 👍 
다만, Recyclerview 이지만 listView 이름을 갖고 있네요

2024-05-02 23:49 UTC, KwonDae commented on app/src/main/java/woowacourse/movie/bindingadapter/BindingAdapter.kt
> +}
바인딩어댑터 활용을 잘 해주셨습니다 👍

2024-05-02 23:49 UTC, KwonDae commented on app/src/main/java/woowacourse/movie/bindingadapter/TableBindingAdapter.kt
> +    seats.seats.forEach { seat ->
좌석들의 좌석들은 어떤 의미를 내포하고 있는건지 처음 읽어보는 동료가 단번에 알아차리게 할 수 있는 방법은 무엇이 있을까요?

2024-05-02 23:49 UTC, KwonDae commented on app/src/main/java/woowacourse/movie/data/DummyMovies.kt
> +    override fun theaterById(theaterId: Long): MovieTheater = theaters.firstOrNull { it.id == theaterId } ?: error("id에 해당하는 극장이 없습니다.")
Error 활용도 좋지만, 레벨1 미션에서 null 활용도 배웠습니다.
id에 해당하는 극장이 없는 시나리오는 에러에 해당할까요?
예를 들어, 사용자를 조회하는데 해당하는 이름의 사용자가 없다는 흐름은 정상적인 시나리오가 아닌걸까요?

2024-05-02 23:49 UTC, KwonDae commented on app/src/main/java/woowacourse/movie/data/IdError.kt
> +    NO_THEATER("%d : id에 해당 하는 극장이 없습니다."),
단순 극장 선택, 영화 예매만을 구현하는데도 IdError가 3개가 생겼네요.
수십, 수백개의 화면을 관리하게 된다면 이곳 IdError의 개수도 수십, 수백개가 되어야 할거에요

2024-05-02 23:49 UTC, KwonDae commented on app/src/main/java/woowacourse/movie/moviereservation/MovieReservationActivity.kt
>          }
Intent 포맷 제공 👍

2024-05-02 23:49 UTC, KwonDae commented on app/src/main/java/woowacourse/movie/screeningmovie/MovieAdapter.kt
>  ) : RecyclerView.Adapter<ScreeningViewHolder>() {
만일, 어떠한 이벤트로 인해 MovieAdapter 데이터가 변경되었다면 다시 어댑터를 생성하여 갈아끼워줘야 할까요?

RecyclerView는 데이터 갱신을 어떤 방식으로 이루어질까요?

2024-05-02 23:49 UTC, KwonDae commented on app/src/main/java/woowacourse/movie/screeningmovie/MovieAdapter.kt
>      private val movies: List<ScreeningItem>,
ScreeningItem 이라는 하나의 타입으로 묶어 model로 type을 구분해주셨군요 👍

2024-05-02 23:49 UTC, KwonDae commented on app/src/main/java/woowacourse/movie/screeningmovie/ScreenMovieUiModelMapper.kt
>          }
ScreenView 은 네이밍 그대로 View라고 에상했는데, movie와 ad를 묶어주는 sealed interface 이네요..?
개선이 필요해 보여요 네이밍은 해당 객체의 가이드 역할을 해줍니다.

2024-05-02 23:49 UTC, KwonDae commented on app/src/main/java/woowacourse/movie/screeningmovie/ScreeningMovieFragment.kt
> +    }
예를 들어, 영화를 불러오는데 10초가 걸리는 이슈로 로딩하는 동안 ProgressBar를 띄워달라는 요구사항이 있다면,
어떻게 처리해야 할까요? 그때까지 adapter 연결을 하지 못할까요?

Recyclerview의 notifySetDataChanged() 키워드가 힌트입니다

2024-05-02 23:49 UTC, KwonDae commented on README.md
<img width="721" alt="image" src="https://github.com/woowacourse/android-movie-theater/assets/33443660/36abe411-4272-412d-9ab7-059b6ea6a793">

ktlint 체크해주세요!

2024-05-02 23:49 UTC, KwonDae commented on app/src/main/java/woowacourse/movie/screeningmovie/ScreenMoviePresenter.kt
> +class ScreenMoviePresenter(
해당 프레젠터 테스트도 진행해주세요!

2024-05-02 23:49 UTC, KwonDae commented on app/src/main/java/woowacourse/movie/screeningmovie/theaters/TheaterPresenter.kt
> +class TheaterPresenter(
TheaterPresenter 테스트도 진행해주세요

2024-05-02 23:49 UTC, KwonDae commented on app/src/main/java/woowacourse/movie/reservationresult/ReservationResultPresenter.kt
> +class ReservationResultPresenter(
ReservationResultPresenter 테스트가 누락됐네요

2024-05-02 23:49 UTC, KwonDae commented on app/src/test/kotlin/SelectSeatPresenterTest.kt
> +    @DisplayName("선택된 좌석들의 예매 가격을 계산하면 뷰에 반영한다.")
Presenter는 비즈니스 로직을 수행하는 장소입니다.
`뷰에 반영한다`는 UiTest 영역이 아닐까요?
`선택된 좌석들의 등급에 맞는 가격을 계산한다`로 가격 계산을 검증해보는건 어떨까요?

2024-05-02 23:49 UTC, KwonDae commented on app/src/test/kotlin/SelectSeatPresenterTest.kt
> +    }
`화면에 나타난다`는 Ui Test 영역입니다.
프레젠터에서 화면에 정말 나타나는지 확인할 수 있을까요?

아래와 같이 테스트 해볼 수 있겠네요
`불러온 극장의 좌석 정보는 극장의 좌석수에 맞게 데이터가 존재한다`

Presenter에서 Verify 를 통한 함수 호출 검증은 가능하지만, 실제로 내부 값에 대한 검증은 어떻게 진행할 수 있을까요?
view.showSeat(emptyList()) 식으로 함수가 호출되었어도 테스트는 통과할거에요.

사용하시는 mockk의 [Capturing](https://mockk.io/#capturing)의 CapturingSlot 과 MutableList를 활용해볼 수 있습니다.

2024-05-02 23:49 UTC, KwonDae commented on app/src/test/kotlin/SelectSeatPresenterTest.kt
> +    }
캡쳐링을 학습해보고 다른 Presenter test에도 적용해볼까요?
모든 프레젠터 테스트에 적용하라는건 아닙니다. 값 검증이 필요하다고 생각되는 부분에 반영해주세요.

진행하시면서 어려운 부분이 있다면 언제든 DM 주세요!

2024-05-02 23:49 UTC, KwonDae commented on app/src/main/res/layout/activity_movie_reservation.xml
> +                android:onClick="@{()->presenter.minusCount(bookingDetail.count)}"
presenter 비즈니스 로직이 변경되거나, onClick 동작이 바뀌어야 한다면 어떤일이 발생할까요?
onClick은 사용자 이벤트 인입 지점으로 View를 통해 해당하는 비즈니스 로직을 수행해야 합니다.
interface를 통해 추상화하여 비즈니스 로직을 수행하는것과 어떤 차이점이 있을까요?

2024-05-02 23:49 UTC, KwonDae commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/BookingDetail.kt
> +data class BookingDetail(
다른 UiModel은 네이밍에서 명시해주고 있지만 여기는 생략되었네요

2024-05-06 19:39 UTC, aprilgom commented on README.md
넵!

2024-05-06 19:39 UTC, aprilgom commented on app/src/androidTest/java/woowacourse/movie/ScreeningMovieFragmentTest.kt
> +    }
구체적인 데이터를 확인하는 대신 뷰가 나오고 있는지 여부를 테스트하도록 바꾸었습니다.

2024-05-06 19:39 UTC, aprilgom commented on app/src/androidTest/java/woowacourse/movie/ScreeningMovieFragmentTest.kt
> +            val listView = fragment.requireView().findViewById<RecyclerView>(R.id.rcv_screening_movie)
이름을 변경해주었습니다.

2024-05-06 19:39 UTC, aprilgom commented on app/src/main/java/woowacourse/movie/bindingadapter/TableBindingAdapter.kt
> +    seats.seats.forEach { seat ->
단순히 인수 이름 seats를 seatsUiModel이나 theater같은 이름으로 고쳐주었어도 좋았겠지만, SeatsUiModel이 제 역할을 못하고 단지 포장지 역할만 하고 있기에 seats.seats같은 이름이 나온다 생각이 들었습니다. 

seatsUiModel을 없애고, Map<Position, SeatUiModel>로 만들어 주었습니다.

2024-05-06 19:39 UTC, aprilgom commented on app/src/main/java/woowacourse/movie/data/DummyMovies.kt
> +    override fun theaterById(theaterId: Long): MovieTheater = theaters.firstOrNull { it.id == theaterId } ?: error("id에 해당하는 극장이 없습니다.")
repository에서 데이터를 조회할 때 해당하는 데이터가 없는 상황 자체는 에러가 아닌 듯 하나, 특정 상황에서 있어야 할 데이터가 없다면 정상적인 시나리오가 아닌 것 같습니다. 예를 들어, 좌석 선택 화면에서 좌석을 선택 후 예약 버튼을 눌러 다음 화면으로 넘어갔을 때, 방금 전에 예매했음에도 예매 데이터가 없는 상황같은 경우는 에러로 생각해야 할 것 같습니다. 

일단 repo에 원하는 데이터가 없을 경우의 처리 책임을 Presenter로 옮겼습니다.

2024-05-06 19:39 UTC, aprilgom commented on app/src/main/java/woowacourse/movie/screeningmovie/MovieAdapter.kt
>  ) : RecyclerView.Adapter<ScreeningViewHolder>() {
MovieAdapter를 매번 새로 만들어 갈아끼우는 대신, 데이터만을 변경하여 넣어주는 updateData 메서드를 만들었습니다. DiffUtil을 사용하여 달라진 아이템만을 갱신하도록 만들었습니다

2024-05-06 19:39 UTC, aprilgom commented on app/src/main/java/woowacourse/movie/screeningmovie/ScreenMovieUiModelMapper.kt
>          }
영화와 광고를 묶게된 건 결국 같은 리스트에 표기하기 위함인데, 이는 뷰 로직이 도메인에 침범해 있다 생각이 들었고, ScreenView의 정체성이 불분명하니 네이밍도 잘 안되고 있다 판단이 들어 삭제하였습니다. 도메인 층에서 묶는 것이 아니라 프레젠테이션 층에서 ListItemUiModel로 묶어주었습니다.

2024-05-06 19:39 UTC, aprilgom commented on app/src/main/java/woowacourse/movie/screeningmovie/ScreeningMovieFragment.kt
> +    }
어댑터를 빈 데이터 셋으로 만들어 어댑터 연결을 먼저 하고, 어댑터의 데이터 셋을 수정 가능하게 만듭니다. 수정한 후에는 notifyDataSetChanged()를 호출해서 리사이클러 뷰에 데이터가 업데이트 되었음을 알리면 됩니다. 어떤 작업일지 상상해보면.. onMovieLoaded 콜백에서 어댑터의 updateData와 notifyDataSet을 호출하면 될 것 같습니다.
 그런데, notifyDataSetChanged는 변경되지 않은 데이터셋도 Ui 업데이트를 모두 해버리는 단점이 있다 들었습니다. 그래서 지금은 DiffUtil을 이용하고 있습니다.

2024-05-06 19:39 UTC, aprilgom commented on app/src/main/java/woowacourse/movie/reservationresult/ReservationResultPresenter.kt
> +class ReservationResultPresenter(
해당하는 Presenter들의 테스트를 몇 가지 만들긴 했으나, 모든 기능을 테스트 하진 못했습니다.. 😵

2024-05-06 19:39 UTC, aprilgom commented on app/src/test/kotlin/SelectSeatPresenterTest.kt
> +    @DisplayName("선택된 좌석들의 예매 가격을 계산하면 뷰에 반영한다.")
좌석 선택에 따른 가격 검증을 해주었습니다.

2024-05-06 19:39 UTC, aprilgom commented on app/src/test/kotlin/SelectSeatPresenterTest.kt
> +    }
문제가 되었던 view.showSeat()의 경우 인수가 List에서 Map으로 바뀌어 mutableList를 이용한 캡처링은 쓸 수 없게 되었습니다. 다른 방법을 찾아보겠습니다..

그 대신 MovieDetailPresenter의 loadMovieDetail 테스트에 일단 적용해 보았는데요, 이해가 부족한 탓인지 캡처링을 적용한 

`verify { view.showMovieInfo(any()) } `
`assertThat(expected).isEqualTo(slot.captured)` 

와

`verify { view.showMovieInfo(expected) } ` 

의 차이를 잘 모르겠습니다. 둘 다 예상하는 값이 인수로 잘 들어갔고 호출되고 있는지를 알 수 있지 않나요? 
애초에 제가 이 테스트에서 뭘 검증하고자 하는지 핀트를 잘 못 잡은 것 같기도 합니다.

2024-05-06 19:39 UTC, aprilgom commented on app/src/main/res/layout/activity_movie_reservation.xml
> +                android:onClick="@{()->presenter.minusCount(bookingDetail.count)}"
view interface를 통해 동작하도록 바꾸었습니다. 이러면 onClick의 동작이 바뀌어야 할 때 바인딩해둔 함수를 바꿀 필요 없이 view interface의 실 구현체의 동작 내용을 바꾸면 됩니다. 지금까지 clicklistener에 presenter의 메서드를 넣어와서, 별 생각 없이 관성적으로 presenter interface 를 바인딩한 것 같습니다.

2024-05-06 19:39 UTC, aprilgom commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/BookingDetail.kt
> +data class BookingDetail(
네이밍을 수정해주었습니다.

2024-05-06 19:44 UTC, aprilgom commented
안녕하세요 제이든님.
네이밍 변경 및 이런 저런 수정이 많아 시간이 좀 지체되었습니다.
Presenter 테스트를 모두 진행하진 못했지만, 더이상 시간을 끄는 건 좋지 못할 것 같아 리뷰 신청 드립니다.

2024-05-07 08:53 UTC, KwonDae commented on app/src/main/res/layout/activity_movie_detail.xml
> +                android:onClick="@{()->view.intendToPlusCount()}"
이곳은 리스너가 아닌 View 로 이벤트를 연결해준 이유가 있었을까요?

2024-05-07 08:53 UTC, KwonDae commented on app/src/test/kotlin/SelectSeatPresenterTest.kt
> +    }
`verify { view.showMovieInfo(expected) }` 만으로도 위 상황에서 해당 함수가 알맞는 파라미터로 호출되었는지 검증은 가능합니다.

다만, 만약 테스트 항목에 `View에 보여질 영화목록은 상영날짜 순으로 정렬되어 있어야 한다` 는 verify로도 검증이 가능할까요?
assert 와 verify는 검증하고자 하는 항목이 다릅니다.
따라서 모든 테스트에 capturing을 사용하는게 아닌 테스트 마다의 특성에 따라 필요한 경우가 있겠죠

2024-05-07 09:00 UTC, KwonDae approved these changes
피드백 양이 많았는데 반영 잘 해주셨습니다  👍 
3,4 단계에서는 구현해야 할 양이 더 많아질텐데요
아직 구현하지 못한 부분 혹은 Presenter 테스트 관련해서는 다음 미션에서 함께 반영해주세요.
끝까지 파이팅입니다!

2024-05-07 09:00 UTC, KwonDae commented on app/src/main/java/woowacourse/movie/movielist/MovieAdapter.kt
> +    ) : DiffUtil.Callback() {
잘 찾아주셔서 DiffUtil 을 적용해주셨네요 좋습니다 👍
DiffUtil 을 사용하는것도 좋지만, 내부적으로 어떤 과정을 통해 개발자에게 편리성을 제공하는지 알고 넘어가면 더욱 좋습니다.

2024-05-07 09:01 UTC, merged