[해시] 1, 2단계 영화 극장 선택 제출합니다.
woowacourse/android-movie-theater pull request #7
Opened 2023-04-27 06:13 UTC by EmilyCh0

안녕하세요! 안드로이드 크루 해시입니다 😄
이번 미션 잘 부탁드립니다!

2023-04-28 02:32 UTC, malibinYun requested changes
1, 2단계 미션 고생 많으셨어요 :)
안드로이드 프레임워크에 대한 공부량이 많아져서 힘드실 것 같아요.
그래도 레벨1에서 배웠던 객체분리!! 꼭 잊지말고 코드를 작성해보세요 :)

피드백 반영 후 다시 리뷰 요청 부탁드릴게요!

2023-04-28 02:32 UTC, malibinYun commented on app/src/androidTest/java/woowacourse/movie/view/MovieMainActivityTest.kt
> +    }
메서드명만 보면, sharedPreference를 어딘가에 할당한다는 의미로 보여요.
구체적으로 어떤 일을 하는 지 이름을 더 고민해보는 건 어떨까요?

또, SharedPreference는 영속성 저장소예요.
실기기에서 이 테스트 코드를 동작시키면 어떻게 될까요?
디비의 값을 가져와서 View의 상태가 바뀌어있는 것 자체는 정말 View의 테스트가 맞는 지 고민해보아요 :)

2023-04-28 02:32 UTC, malibinYun commented on app/src/androidTest/java/woowacourse/movie/view/SeatSelectionActivityTest.kt
> +    )
`@Before`를 사용해보는 건 어떨까요?

2023-04-28 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/util/ParcelableExtension.kt
> +}
Parcelable과 Serializable 을 중복으로 사용한 이유가 궁금해요 :)
중복으로 사용하면 어떤 문제가 생길 수 있을까요?

2023-04-28 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/AlarmController.kt
> +        val alarmManager = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
AlarmManager를 매번 호출할 때마다 찾아오네요.
한 번만 찾아오는 방법이 있을까요?

2023-04-28 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/AlarmController.kt
> +    private fun getPendingIntent(reservation: ReservationUiModel): PendingIntent {
get은 새로 만든다는 의미를 주긴 어려워보여요.
또, 어떤 pendingIntent인지도 구체적으로 적어보는 건 어떨까요?

2023-04-28 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/AlarmController.kt
> +            )
let 스코프 함수를 선택한 이유가 무엇인가요?
다른 스코프 함수들과 어떻게 다를까요?

2023-04-28 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/ReservationCompletedActivity.kt
> +                    startActivity(intent)
이 로직은 중복되어있네요 :)
재활용해볼 수 있을까요?

2023-04-28 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/ReservationCompletedActivity.kt
> +        }
액티비티 스스로의 인텐트를 만드는 건 좋아보이는데, 반드시 ReservationUiModel이 필요한 intent만이 필요할지는 미지수네요.
다른 값을 넣어야하는 경우가 생길 때마다 이러한 새 메서드가 생겨날 것이 우려되네요 :)

2023-04-28 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/moviemain/MovieMainActivity.kt
> +                    return@setOnItemSelectedListener true
매번 탭을 누를 때마다 새로운 Fragment를 만들어주어야할까요?
https://developer.android.com/guide/fragments/transactions#add-remove
이 문서를 잘 참고해보세요 :)

2023-04-28 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/moviemain/MovieMainActivity.kt
> +    }
이 일들은 이 액티비티의 일일까요?

2023-04-28 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/moviemain/MovieMainActivity.kt
> +        }
sharedPreferences의 데이터를 다루는 객체를 분리해보는 건 어떨까요?

2023-04-28 02:32 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/moviemain/setting/SettingFragment.kt
> +            editor.putBoolean(IS_ALARM_ON, false).apply()
토글이 누릴 때마다 알람을 등록해야할까요?
사용자가 광클하면 어떤 일이 발생할까요?

2023-04-30 01:44 UTC, EmilyCh0 commented on app/src/androidTest/java/woowacourse/movie/view/MovieMainActivityTest.kt
> +    }
테스트 코드를 동작시키면 실제 앱의 SharedPreference 값에 영향을 줍니다. 그리고 SharedPreference에 저장된 값에 따른 결과를 테스트하는 것은 UI 테스트가 아니라고 생각되어서 해당 테스트를 제거했습니다 😅

2023-04-30 01:44 UTC, EmilyCh0 commented on app/src/androidTest/java/woowacourse/movie/view/SeatSelectionActivityTest.kt
> +    )
ActivityScenarioRule 생성 시점에 인텐트를 전달해야 돼서 `@Before`를 사용하지 못했습니다 🥲 다른 방법이 있는 걸까요?

2023-04-30 01:46 UTC, EmilyCh0 commented on app/src/main/java/woowacourse/movie/util/ParcelableExtension.kt
> +}
LocalDate가 Serializable을 implement하고 있어서 `onSaveInstanceState`에서 LocalDate를 저장할 때 Serializable을 사용했습니다..!
한 data class에 Serializable과 Parcelable을 중복으로 사용한다면 직렬화 방식의 차이가 있어서 문제가 발생할 수도 있을 것 같지만 현재는 이 두 가지를 동시에 사용하지는 않기에 문제가 없을 것이라고 생각합니다.
하지만 데이터를 일관성 있게 직렬화하는 것이 좋을 것 같아 기존에 만들어 둔 `ReservationOptions`을 Parcelable로 저장하도록 변경했습니다!

2023-04-30 01:48 UTC, EmilyCh0 commented on app/src/main/java/woowacourse/movie/view/AlarmController.kt
> +            )
최종적으로 생성된 PendingIntent를 리턴해야 해서 let을 사용했었는데 코드 가독성이 떨어지는 것 같아 수정했습니다!

2023-04-30 01:52 UTC, EmilyCh0 commented on app/src/main/java/woowacourse/movie/view/ReservationCompletedActivity.kt
> +        }
ReservationCompletedActivity는 예매 완료된 정보를 보여주는 화면이기에 시작할 때 ReservationUiModel 값이 반드시 필요하다고 생각합니다. 요구사항이 변경되어 다른 값이 필요하다면 경우에 따라
필수적인 값이면 기존 메서드인 newIntent()를 수정해 추가적인 값을 인자로 받거나,
선택적으로 전달하는 값이면 newIntent()를 호출하는 쪽에서 putExtra로 추가하거나, newIntent()의 인자 값을 nullable하게 받거나,
필수적인 값인데 기존 메서드의 기능도 필요한 경우 Intent를 생성하는 메서드를 하나 더 추가해야 할 것 같습니다.

저는 이 메서드가 이 화면에 필수적으로 필요한 값들을 넘기지 않게되는 실수도 방지하고, putExtra()에 실수로 다른 키 값을 넣는 것도 방지할 수 있어서 좋은 방식이라고 생각했는데 실제 큰 규모의 프로그램에서는 이런 방식이 불필요한 코드들을 만들어내게 되는 걸까요?

2023-04-30 01:59 UTC, EmilyCh0 commented on app/src/main/java/woowacourse/movie/view/moviemain/setting/SettingFragment.kt
> +            editor.putBoolean(IS_ALARM_ON, false).apply()
광클했을 때 문제가 발생할 여지가 있다는 점(동기화가 안되는 등..)은 인지하고 있었지만
1. 알림을 cancel 및 재등록하기
2. 취소하지 않고, sharedPreferences에 저장된 상태에 따라 알림을 띄우지 않기(무시하기)

두 옵션을 고려했을 때 두 번째 방식은 알림을 끈 상태에서도 예약을 생성할 때마다 알림이 등록되고, 등록된 알림을 계속 receive 하기 때문에 불필요한 리소스가 낭비된다고 생각해서 1번 방식을 택했습니다. 알림이 안정적으로 작동하는 2번 방식으로 하는 것이 좋을까요? 아니면 아예 다른 방식으로 접근해야 하는 것일까요? 🤨
현재는 1번 방식을 유지하면서 대신 onStop() 시점에 한 번만 알림 취소 or 재등록 하도록 수정했는데, 적절한 해결 방법인지는 잘 모르겠습니다.. 😅

2023-04-30 15:52 UTC, malibinYun approved these changes
피드백 반영 고생 많으셨어요 :)
다음은 아키텍처 관련 내용이라 꽤 어려울 수 있으니 빠르게 머지하겠습니다.
굉장히 고민을 많이 하시고 아키텍처를 적용해보세요 :)
남겨둔 피드백은 다음 미션에 반영해주세요!

2023-04-30 15:52 UTC, malibinYun commented on app/src/androidTest/java/woowacourse/movie/view/SeatSelectionActivityTest.kt
> +    )
이 부분은 제가 `ServiceTestRule`과 착각해서 각 activity를 실행시킬 때마다 다른 intent를 넘겨줄 수 있을 것으로 잘못 생각했어요.

`ActivityScenarioRule`에는 해당 메서드가 존재하지 않네요. 내부를 잘 들여다보니, 생성자로부터 intent를 한 번 넘겨주면 해당 intent로 액티비티를 실행시켜버려서 바꿀 방법이 없네요. 혼동을 드려서 죄송해요 😥

그래도 방법이 없을까, 고민을 많이 해봤는데요, 꽤나 어려운 방법일 것 같아서 방법만 공유해봅니다 😅

Rule class는 사실 before, after에 미리 해야 할 일을 모아 둔 별 거 없는 class 랍니다. `ActivityScenarioRule`는 `ExternalResource`를 상속 받고 있어요. 그래서 테스트를 실행할 때 `@Before` 붙어있는 메서드를 자동으로 실행해 주듯이, 이 내부에서도 실행시켜주어요 :)

`ActivityScenarioRule`의 내부는 생각보다 매우 간단한데요, 4개의 생성자를 통해 여러 동작을 지원하고, 해당 동작을 매 테스트 때마다 before를 통해 실행시켜줍니다.

다행스럽게도 내부에서 사용하는 `ActivityScenario` class는 public 이에요. 그렇기에 이 Rule class를 참고하고, intent 객체를 lazy하게 가져오게 만드는 기능을 추가해서 직접 Rule class를 만들어내면 충분히 intent를 교체할 수 있게 되어요.

`ActivityScenarioRule`이 final class 여서 상속을 받아 개조하는 방법은 통하지 않겠더라구요.

이 부분은 꼭 시도해보시지 않아도 좋아요.
간단히 접근할 수 없는 부분이었는데, 쉽게 접근할 수 있는 분야처럼 말씀드려 혼란을 드린 거 같아 죄송한 마음이에요.
많은 고민을 하셨지만 답을 찾지 못해 답답하실 것 같아서, 해결 방법 중 하나를 대신 고민해서 공유드려요 :)

2023-04-30 15:52 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/AlarmPreference.kt
> +    }
get put Boolean은, 알람의 어떤 정보를 의미하는 지 담기에는 부족해 보여요.
더 의미를 부여해보는 건 어떨까요?

또, 외부에서 key 값에 대한 관심사를 없애보는 건 어떨까요?

2023-04-30 15:52 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/AlarmController.kt
> +    }
AlarmController에서 ReservationUiModel를 알아야할까요?
영화 예약 이외에 다른 시간 기능을 활용해야 할 때가 되면 어떤 변경점이 생길까요?

2023-04-30 15:52 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/AlarmController.kt
> +    }
Notification에 대한 역할이 분산되어있어 보여요.
하나의 협력을 하는 객체로 만들어보는 건 어떨까요?

2023-04-30 15:52 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/moviemain/MovieMainActivity.kt
> +        }
객체 지향 생활 체조의 들여쓰기 규칙을 최대한 지켜보았으면 좋겠어요 :)

2023-04-30 15:52 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/moviemain/MovieMainActivity.kt
> +    }
여러 권한을 요청하는 ActivityResultContract가 따로 존재합니다.
또, ActivityResultContracts.RequestPermission를 활용할 때에 self permission 체크를 반드시 해야할까요?

2023-04-30 15:52 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/moviemain/MovieMainActivity.kt
> +        val sharedPreferences = AlarmPreference(this)
AlarmPreference가 필요할 때마다 생성해야할까요? 싱글톤 객체로 만들어 활용해보세요 :)

2023-04-30 15:52 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/moviemain/movielist/MovieListFragment.kt
> +    }
리소스 아이디를 파라미터로 가지는 Fragment 생성자에 대해서 알아보아요 :)

2023-04-30 15:52 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/moviemain/movielist/MovieListFragment.kt
> +        return dataList
코틀린의 확장 함수들을 잘 활용해서 mutableListOf등을 직접 생성하지 않게 코드를 구성해보세요🙂

2023-04-30 15:52 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/moviemain/reservationlist/ReservationListAdapter.kt
> +    }
이러한 종류의 interface들은 안드로이드 프레임워크에서는 어떤 이름을 붙이고 있을까요?

2023-04-30 15:52 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/moviemain/setting/SettingFragment.kt
> +    ) { isGranted: Boolean ->
멤버변수의 위치는 메서드 위에 위치해야합니다 :)

높은 os버전에서 권한을 3번 이상 거절하면 어떤 현상이 발생할까요?

2023-04-30 15:52 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/moviemain/setting/SettingFragment.kt
> +    }
onStop에 설정 값에 대해 다루는 건 위험할 수 있어요.

생명주기 함수가 정상적으로 불리지 않고 앱이 비정상 종료되는 경우가 존재할 수도 있고,
절묘한 타이밍에 끔을 체크했지만 화면을 벗어나지 않아 켠 상태의 액션이 일어날 수도 있겠지요 :)

2023-04-30 15:52 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/seatselection/AlarmReceiver.kt
> +        }
실제 널이라면 빈 문자열 등을 표시해주는 게 올바른 동작일까요?

2023-04-30 15:52 UTC, malibinYun commented on app/src/androidTest/java/woowacourse/movie/view/MovieMainActivityTest.kt
> +    }
스위치가 잘 동작하는 지 정도는 테스트해도 괜찮다고 생각이 드네요 :)

2023-04-30 15:53 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/util/ParcelableExtension.kt
> +}
좋아요 👍
Serializable과 Parcelable의 차이에 대해서 꼭 학습하셨으면 좋겠네요 🙂

2023-04-30 16:05 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/ReservationCompletedActivity.kt
> +        }
newIntent() 조차도 `putExtra()에 실수로 다른 키 값을 넣는 것도 방지할 수 있다` 라고 하기엔 어렵습니다. `newIntent()를 수정해 추가적인 값을 인자로 받거나` 여기에서 해당 부분을 충분히 실수할 수 있겠지요.
또, 특정 값이 반드시 Intent에 들어가야 함은 다른 개발자가 한 번에 알기에는 쉽지 않을 거예요.

Intent 가지고는 제약이 어렵다는 의견이에요.

해시 의도 대로 특정 값을 반드시 보내야 하는 기능을 작성해야한다면, 아래 같은 형식의 메서드를 작성해볼 수 있겠어요.
```
companion object {
    fun start(context: Context, reservation: ReservationUiModel) {
        ~~~
        context.startActivity()
    }
}
```
다만, 이전 의견 처럼, `다른 값을 넣어야하는 경우가 생길 때마다 이러한 새 메서드가 생겨날 것이 우려` 되어 더 다른 방법에 대해 고민했을 거예요. ReservationUiModel 에서 한 개 혹은 여러 값이 다른 model을 받아야 하는 경우가 생길 수 있겠지요.

이러한 화면 전환에 대한 전략은 매우 다양하게 존재할 수 있어서, 정답은 없답니다. 🙂
어떠한 의견과 어떠한 제약 조건이 생겼을 때, 다른 전략에 대해 충분히 고민해보고 다양한 방법을 고안해보셨으면 좋겠어요 😊

2023-04-30 16:14 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/view/moviemain/setting/SettingFragment.kt
> +            editor.putBoolean(IS_ALARM_ON, false).apply()
아래 시나리오에서는 어떻게 동작해야할까요?

1. 설정에서 알람 기능을 껐어요.
2. 영화를 예매합니다 (알람을 등록합니다)
3. 앱을 종료합니다
4. 앱을 실행해서 알람 기능을 켭니다.

또, 객체가 적절한 일을 하고 있는 지 충분히 고민해보세요.
예를 들면,
설정에서 알림을 껐지만, 알람이 비정상 등록되더라도, 등록 된 알람을 울려야할까요?

2023-04-30 16:15 UTC, merged