[아크] 1, 2단계 영화 극장 선택 제출합니다.
woowacourse/android-movie-theater pull request #8
Opened 2023-04-27 07:12 UTC by re4rk

안녕하세요!! 리뷰어님!!
이번 미션동안 잘 부탁드립니다!!

2023-04-27 13:33 UTC, galcyurio requested changes
전체적으로 코드 가독성이 아주 좋았습니다 💯
피드백을 남겨두었으니 반영 후 다시 요청해주세요.

2023-04-27 13:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/MyApplication.kt
> +        lateinit var prefs: PreferenceUtil
좋지 않은 패턴입니다. 만약 `MyApplication.prefs`에 접근하는 코드를 테스트하려고 한다면 반드시 사전작업으로 MyApplication을 초기화해야 하기 때문입니다.

2023-04-27 13:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/PreferenceUtil.kt
> +class PreferenceUtil(context: Context) {
이 클래스는 Util성 함수들이 모여있지 않기 때문에 이름과 어울리지 않습니다.
DefaultPreference, PreferenceImpl과 같은 이름으로 변경해주세요.

2023-04-27 13:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/data/TicketsRepository.kt
> +    private val tickets: MutableList<TicketsState> = mutableListOf()
[공식 컨벤션](https://kotlinlang.org/docs/coding-conventions.html#class-layout)에 따르면 클래스 레이아웃은 아래와 같은 순서로 배치합니다.

1. Property declarations and initializer blocks
2. Secondary constructors
3. Method declarations
4. Companion object

2023-04-27 13:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/model/TicketOptState.kt
> +data class TicketOptState(
opt는 어떤 의미일까요?
이름을 지을 때는 다른 개발자들도 이해하기 쉽게 생략을 피해주세요.

2023-04-27 13:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/util/Permissions.kt
> +}
권한 관련 기능들을 확장 함수로 분리 :+1:

2023-04-27 13:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/util/NotificationExt.kt
> +val atomicNotifyId = AtomicInteger(0x001)
16진수를 쓰신 이유가 있나요?

2023-04-27 13:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/util/NotificationExt.kt
> +        return -1
`-1`은 어떤 역할인가요?

2023-04-27 13:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/ui/main/viewHolder/TicketsViewHolder.kt
> +class TicketsViewHolder(view: View) : ItemViewHolder(view) {
View 캐시부터 bind() 함수 분리, 각 아이템별 Model 까지 ViewHolder 설계가 좋네요 👍️

2023-04-27 13:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/ui/main/MainActivity.kt
> +    }
코드 가독성이 좋네요! 💯

2023-04-27 13:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/ui/fragment/setting/SettingFragment.kt
> +        context?.let {
`onViewCreated()`와 같이 일반적으로 알려져있는 생명주기인 경우에는 `requireContext()`를 사용해도 안전합니다.

주의해야 하는 경우는 네트워크 요청과 같이 비동기적으로 응답이 왔을 때, 사용자가 화면을 꺼버리는 경우들이 해당됩니다.
하지만 이런 경우들도 요즘은 RxJava, RxAndroid 또는 kotlinx.coroutines와 같은 도구를 쓰면 안드로이드의 생명주기에 맞게끔 알아서 취소 처리를 해주어서 사실상 문제가 되는 경우는 없다고 봐도 됩니다.

2023-04-27 13:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/ui/confirm/AlarmReceiver.kt
> +    }
indent가 너무 깊이 들어가네요. 최대 2단계로 유지해볼까요?

2023-04-27 13:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/ui/confirm/ReservationConfirmActivity.kt
> +        val tickets = tickets.copy(dateTime = LocalDateTime.of(0, 4, 26, 17, 47, 30))
이 코드는 실수로 테스트하다가 추가된 것으로 보이네요.

2023-04-27 13:33 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/ui/confirm/ReservationConfirmActivity.kt
> +            calendar.timeInMillis - 30 * 60 * 1000,
calendar 대신 java.time 패키지의 기능을 활용해보세요.


<details>
<summary><h2>힌트<h2></summary>
<br>

- LocalDateTime.minusMinutes()
- java.time.Duration.between()
- java.time.Duration.toKotlinDuration()
- kotlin.time.Duration.inWholeMilliseconds

</details>

2023-04-27 23:31 UTC, re4rk commented on app/src/main/java/woowacourse/movie/ui/confirm/ReservationConfirmActivity.kt
> +        val tickets = tickets.copy(dateTime = LocalDateTime.of(0, 4, 26, 17, 47, 30))
바로 제거 하였습니다!!

2023-04-27 23:36 UTC, re4rk commented on app/src/main/java/woowacourse/movie/model/TicketOptState.kt
> +data class TicketOptState(
팀원과 상의하여 option이라는 의미로 액티비티 간의 데이터를 이동 시킬 때 사용하고자 하였습니다!
수정 후에는 사용하는 액티비티명과 동일하게 변경하였습니다!

2023-04-28 17:09 UTC, galcyurio approved these changes
의도대로 피드백 잘 반영해주셨네요 👍 
역할별로 객체로 분리하거나 확장함수로 잘 분리해주셔서 가독성이 좋았습니다.
반영되지 않은 피드백이 있는데 확인 후 다음 단계에 반영해주세요!

2023-04-28 17:09 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/util/NotificationExt.kt
> +val atomicNotifyId = AtomicInteger(0x001)
코멘트 확인해주세요~

2023-04-28 17:09 UTC, merged