[영화 극장 선택] 호두 3,4단계 미션 제출합니다.
woowacourse/android-movie-theater pull request #95
Opened 2024-05-13 08:49 UTC by Junyoung-WON

안녕하세요! 두루!
3, 4단계의 예매내역 저장, 알림 기능 미션 제출합니다.
하지만 기능 구현에 먼저 힘쓰느라, 리팩터링과 테스트 코드가 제대로 되어있지 않습니다.
그리고 알람 기능도 지금 제대로 동작하지 않는 것 같아요...
시간이 없으니 먼저 PR을 보내고, 이후에도 계속 기능 수정과 리팩터링 진행하겠습니다.
우선 현재 기능 구현한 코드까지만 피드백을 해주시면 감사하겠습니다!

## 개선해야 할 점

### 알림 클릭 시 실제 예매한 시간과 다름
알림은 설정한 시간에 정상적으로 오지만, 알림을 통해 예매 확인 화면으로 이동하면, 다른 시간대가 나타납니다. 지금 데이터로서는 09:00이 상영 시작으로 고정되어 나타나고 있습니다. 아직 원인을 찾지 못했는데, 다음 PR에서 꼭 개선하겠습니다!

### 복잡한 도메인(상영 시간 및 날짜)
티켓 미션 때에 도메인 설계를 너무 깊고 복잡하게 진행하여서, 현재 불필요한 기능들도 많고, 이에 따라 위와 같은 오류들이 나타나는 것 같습니다. 도메인 설계를 조금 더 가볍게 변경할 필요가 있는 것 같습니다.

### 알림 권한 설정 기능
알림 권한을 설정하는 기능이 현재 동작하지 않고 있습니다. 앱 자체 설정 화면에서 설정하든 하지 않든 알림을 계속 받을 수 있습니다.

## 커밋 비교 링크
https://github.com/Junyoung-WON/android-movie-theater/compare/f76e985034dad4ac7f22698b5ba14077406f9fe3..89298cfb9896f84a98384ab591fa068469808625

2024-05-13 11:47 UTC, Gyuil-Hwnag requested changes
호두 안녕하세요!

해당 미션 구현 고생 많으셨습니다!
이전 1, 2 단계의 리뷰 반영하면서 3, 4의 내용 구현 너무 잘해주셨습니다 💯

말씀해주신대로, 현재 시간이 부족하여 3, 4단계 구현에 대해서 치중을 하였으니 이번 요청에서는 리팩토링, 리뷰 반영, 테스트 코드를 중심으로 살펴보면 좋을 것 같다는 생각이 듭니다!
고민해보시면 좋을만한 내용들 코멘트를 달았으니 확인해주시면 감사하겠습니다.

추가적으로 모든 내용을 반영하다 보면, 시간이 모자랄 수 있으니 호두의 판단하에 중요하다고 생각되는 우선순위를 정하여 반영을 해보는 것도 좋을 것 같습니다😀
(추후 반영할 내용들에 대해서는 고민후에 코멘트를 남겨두고 차차 반영을 해나가는 방식도 좋을 것 같다는 생각이 듭니다)

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 
화이팅입니다💪

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on README.md
> +## STEP 3
README 작성 좋습니다~👍

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.USE_EXACT_ALARM" />
권한 설정 좋습니다~👍
권한 관련 키워드가 나왔으니, 한번 알아두고 가면 좋을 내용이 있어서 남겨두었습니다!
Android는 OS별로도 권한이 사라지고, 변경이 되는 경우가 있어서 이를 위해 maxSdkVersion등의 설정도 추가할 수 있습니다!
https://developer.android.com/guide/topics/manifest/uses-permission-element

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/alarm/AlarmReceiver.kt
> +    override fun onReceive(
AlarmReceiver관련 작성 잘해주셨네요~👍
추후 시간이 남을 때 BroadcastReceiver() 관련해서 한번 살펴보고 가는 것도 좋을 것 같다는 생각이 듭니다!

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/alarm/MovieStartAlarmManager.kt
> +            )
PR에도 남겨주셨듯이, 알림이 정확한 시간에 안오는 이슈가 있더라구요🥲
현재 단계에서는 수정이 필요한 내용은 아니며, 추후 호두가 알림 관련해서 개발을 하실 때 도움이 될 만한 내용인 것 같아서 코멘트 남겨두었습니다!💪

`alarmManager.setExactAndAllowWhileIdle()`의 경우 정확한 시간에 알림이 안울리는 이슈가 있습니다.
시간을 정확하게 하기 위해서`alarmManager.canScheduleExactAlarms()`를 사용한다면, 사용자가 앱에 대해서 `알림 및 리마인더`를 설정해줘야 합니다.
`사용자에게 알림 허용 -> 알림 및 리마인더 설정 2댑스` vs `시간이 부정확하더라도 1댑스로 기능 활성화` 와 같은 고민이 생기실텐데, 어떤 구현을 하는것이 좋을지 한번 고민해보면 추후에 도움이 될 것 같다는 생각이 듭니다!

이전에 저도 고민 했던 내용이 있어서 링크 첨부하였습니다!
[알림 기능1](https://github.com/Gyuil-Hwnag/compose_study/pull/24)
[알림 기능2](https://github.com/Gyuil-Hwnag/compose_study/pull/25)

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/alarm/MovieStartNotificationManager.kt
> +        }
버전별 분기처리 좋습니다~👍

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/alarm/MovieStartNotificationManager.kt
> +            .setContentText("영화 상영 시작 30분 전입니다.")
해당 하드코딩으로 들어간 내용에 대해서는 Android Resource를 활용하도록 해보는 것은 어떤가 라는 생각이 듭니다!💪

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/view/bottomNavigationBar/HomeFragment.kt
> +        binding.movieList.layoutManager = LinearLayoutManager(context)
`binding.movieList.layoutManager = LinearLayoutManager(context)` 해당 내용은 xml 내에서도 선언이 가능하니 참고 부탁드립니다~💪

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/view/bottomNavigationBar/NavigationActivity.kt
> +
Permission 에 대한 처리 좋습니다~👍

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/view/bottomNavigationBar/NavigationActivity.kt
>      }
Notification 권한에 대한 여부를 앱이 실행될 때 묻도록 설정을 하신 이유가 궁금합니다🤔
사용성 관점인 것 같아서 호두의 자유로운 의견을 공유해주세요~💪

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/view/bottomNavigationBar/NavigationActivity.kt
> +                }
버전별 처리 좋습니다~👍

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/view/bottomNavigationBar/SettingFragment.kt
> +        }
Activity 에서 Preference에 대해서 직접적으로 접근을 하지 않고, 함수또는 객체를 통해서 설정을 해보도록 하는 것은 어떤가 라는 생각이 듭니다!💪

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/view/bottomNavigationBar/SettingFragment.kt
> +    private var notificationPreference: SwitchPreferenceCompat? = null
`PreferenceFragmentCompat()`의 활용 너무 잘해주셨습니다~
`PreferenceFragmentCompat()`를 활용하지 않고 구현을 하려면 어떻게 해야 할지 한번 고민해보면 좋을 것 같다는 생각이 듭니다!💪

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/view/reservation/detail/MovieDetailPresenterImpl.kt
>      val theaterId: Int,
movieId, theaterId 를 Preference를 인스턴스 생성시에 부 생성자로 반드시 받아야 하는 이유가 있을지 궁금합니다!🤔

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/view/reservation/result/ReservationResultActivity.kt
>          binding.data = ticket
non-nullable 하다고 강제롤 하는 !!는 자칫 오류를 유발하는 구현이 될 수 있겠다는 생각이 듭니다🥲
해당 내용을 좀 더 유연하게 처리해 볼 수 있을 것 같다는 생각이 듭니다!
추가적으로 `getParcelableExtra()`에 대한 버전별 분기처리도 해보면 좋을 것 같다는 생각이 듭니다~💪

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/res/values/dimens.xml
> +    <dimen name="margin_item_between_title_date">6dp</dimen>
dimen의 활용 좋습니다~👍

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/view/reservation/seat/SeatSelectionPresenterImpl.kt
>      reservationCount: Int,
Presenter에 대한 전반적인 코멘트 입니다~
Presenter에 대한 테스트도 작성을 해보면 좋을 것 같다는 생각이 듭니다!💪

2024-05-13 11:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/view/reservation/seat/SeatSelectionActivity.kt
> +    private lateinit var reservationDatabase: ReservationDatabase
새롭게 추가된 Activity, Fragment에 대한 전반적인 코멘트 입니다!
Activity, Fragment에 대한 테스트도 작성을 해보면 좋을 것 같다는 생각이 듭니다!💪

2024-05-14 00:28 UTC, Junyoung-WON commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.USE_EXACT_ALARM" />
좋은 레퍼런스 공유 감사드립니다!! 😄

2024-05-14 00:54 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/movie/alarm/MovieStartAlarmManager.kt
> +            )
AlarmManager에 리시버에게 보낼 알람을 설정하는 메서드가 정말 다양하게 있었네요...! 정확한 시간에 울리는 알람은 사용자가 리마인더에 대한 설정을 해주어야 하는군요. 꼭 참고하여서, 나중에 관련 기능을 구현할 때 잘 고민하고 활용해보겠습니다😊

2024-05-14 00:55 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/movie/alarm/MovieStartNotificationManager.kt
> +            .setContentText("영화 상영 시작 30분 전입니다.")
기능에 신경쓰다가 리팩터링을 못하고 제출했네요😅 string 리소스를 활용하도록 해보겠습니다!

2024-05-16 10:49 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/movie/presentation/view/bottomNavigationBar/NavigationActivity.kt
>      }
영화가 시작되기 30분 전임을 알려주는 알림은 구현한 앱이 갖고 있는 편의 기능 중 하나입니다.
일부 사용자는 이런 기능을 필요로 하고, 해당 기능이 정상적으로 잘 동작하기를 원할 수도 있다고 생각합니다.
그래서 알림 기능의 동작 여부를 확실히 정할 수 있도록, 앱을 실행했을 때에 사용자에게 알림에 대한 권한을 묻는 것이 더 적합하다고 생각했습니다..!

2024-05-16 11:03 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/movie/presentation/view/bottomNavigationBar/NavigationActivity.kt
>      }
물론 이러한 구현은 다른 일부 사용자들의 사용 경험을 떨어뜨릴 수 있을 것 같습니다.
그래서 예약이 완료되고 난 후 예매 결과를 확인하는 화면에서 알림에 대한 권한을 얻도록 묻는 것도 좋은 방법이 될 것 같네요!

2024-05-18 05:44 UTC, Junyoung-WON commented
안녕하세요, 두루!
극장 미션 피드백 제출이 너무 늦어졌네요.
이전에 구현 못했던 기능 요구사항을 최대한 만족하고
UI테스트와 Presenter 테스트도 전부는 아니지만 작성해보았습니다.
지금 진행중인 미션에도 집중하고싶어서
이전 미션은 여기까지만 진행하고 마무리짓고 싶습니다...!
두루와 많은 피드백을 주고받지 못해서 너무 아쉽지만,
그럼에도 두루가 제게 가르쳐주신 것들 모두 감사하게 생각하고 있습니다!
두루가 알려주신 몇가지 팁들과 조언들을 활용해서
이후 미션에서도 잘 적용할 수 있도록 열심히 공부하겠습니다!

2024-05-18 06:17 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/view/bottomNavigationBar/NavigationActivity.kt
>      }
@Junyoung-WON 
타당한 의견 좋습니다~
아마 실무에서는 이러한 권한을 묻는 정책들에 대해서, 고민을 해볼 기회가 있을 것 같은데 그럴 때 호두의 생각을 잘 얘기해본다면 좋은 사용자 경험을 제공할 수 있을 것 같습니다😀

2024-05-18 06:29 UTC, Gyuil-Hwnag approved these changes
호두 안녕하세요!
미션 너무 고생 많으셨습니다! 👏

리뷰 반영 정말 잘 해주셨어요💯
구현을 하시면서 여러가지 고민을 하셨을 텐데 다음 미션 에서도 잘 적용을 하면서 발전해 나가시길 바라겠습니다😆

다음 미션 진행을 위하여 해당 미션은 여기서 머지하도록 하겠습니다.
도움이 될만한 내용들 코멘트 달았으니 확인해보셔도 좋을 것 같습니다!

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏
앞으로도 응원하겠습니다 💪

2024-05-18 06:29 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/view/bottomNavigationBar/SettingFragment.kt
> +    private var notificationPreference: SwitchPreferenceCompat? = null
`Context`라는 키워드가 나왔으니, Context 라는 키워드에 대해서 한번 정리를 해본다면, 추후에 많은 도움이 될 것 같다는 생각이 듭니다~💪
추가적으로 requireContext()는 어떤 Context를 가져오는지에 대해서 살펴본다면, 해당 인스턴스가 싱글톤으로 사용되는지 좀 더 명확하게 구현을 해볼 수 있겠다는 생각이 듭니다!

2024-05-18 06:29 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/sharedpreference/MovieSharedPreferences.kt
> +    private val prefs = getSharedPreferences(context)
호두가 SharedPreference를 사용하려고 했던 의도에 맞게 사용을 하려면, class 가 나을지, object 가 나을지도 한번 살펴보면 좋을 것 같다는 생각이 듭니다~💪

2024-05-18 06:29 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/alarm/MovieStartNotificationManager.kt
> +            val descriptionText = context.getString(R.string.notification_channel_description)
Android Resource의 활용 좋습니다~👍

2024-05-18 06:29 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/alarm/MovieStartNotificationManager.kt
> +            val channelId = context.getString(R.string.notification_channel_id)
버전별 분기처리 잘해주셨네요~👍

2024-05-18 06:29 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/alarm/MovieStartNotificationManager.kt
> +        ticket?.ticketId?.let { notificationManager.notify(it.toInt(), notificationBuilder.build()) }
해당 내용은 모두 ticket이 null 이 나일 때 사용되는 것이므로, 하나로 같이 묶어 보는 형식으로 한다면, 하단에 있는 불필요한 null check 를 없애볼 수 있겠다는 생각도 듭니다~💪

2024-05-18 06:29 UTC, Gyuil-Hwnag commented on app/src/test/java/woowacourse/movie/presenter/MovieDetailPresenterTest.kt
> +    private lateinit var view: MovieDetailContract.View
Presenter에 대한 테스트 코드 잘 작성해주셨네요~👍

2024-05-18 06:29 UTC, Gyuil-Hwnag commented on app/src/test/java/woowacourse/movie/presenter/MovieDetailPresenterTest.kt
> +    }
given, when, then 으로 테스트 함수를 너무 잘 구현해주셨네요~👍

2024-05-18 06:29 UTC, Gyuil-Hwnag commented on app/src/androidTest/java/woowacourse/movie/presentation/view/reservation/seat/SeatSelectionActivityTest.kt
> +    private val intent: Intent = seatSelectionActivityIntent(testContext)
추후에 시간이 난다면, Fragment 에 대한 테스트 코드를 작성해봐도 좋은 경험이 될 것 같다는 생각이 듭니다~👍

2024-05-18 06:29 UTC, merged